import { PrismaPg } from "@prisma/adapter-pg"
import { PrismaClient } from "@prisma/client"

const url = process.env.DATABASE_URL || "postgresql://postgres:postgres@localhost:5432/aiverse"
const adapter = new PrismaPg({ connectionString: url })
const prisma = new PrismaClient({ adapter })

const ALL_TOOLS = [
  // === CHAT AI (20+) ===
  { name: "ChatGPT", slug: "chatgpt", tagline: "Advanced AI chatbot by OpenAI", description: "ChatGPT is an AI-powered chatbot for conversations, writing, coding, and problem-solving.", websiteUrl: "https://chat.openai.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=openai.com&sz=64", cats: ["chat-ai"], isFeatured: true, score: 100 },
  { name: "Claude", slug: "claude", tagline: "Anthropic's helpful AI assistant", description: "Claude excels at analysis, long-form content, and thoughtful conversations.", websiteUrl: "https://claude.ai", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=claude.ai&sz=64", cats: ["chat-ai"], isFeatured: true, score: 95 },
  { name: "Perplexity AI", slug: "perplexity-ai", tagline: "AI-powered answer engine", description: "Perplexity AI provides accurate answers with real-time web search and citations.", websiteUrl: "https://perplexity.ai", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=perplexity.ai&sz=64", cats: ["chat-ai"], isFeatured: true, score: 90 },
  { name: "Gemini", slug: "gemini", tagline: "Google's most capable AI model", description: "Gemini is Google's multimodal AI model that understands text, images, audio, video, and code.", websiteUrl: "https://gemini.google.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=gemini.google.com&sz=64", cats: ["chat-ai"], isFeatured: true, score: 88 },
  { name: "Grok", slug: "grok", tagline: "xAI's conversational AI with real-time knowledge", description: "Grok is an AI chatbot developed by xAI with access to real-time knowledge via the X platform.", websiteUrl: "https://grok.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=x.ai&sz=64", cats: ["chat-ai"], score: 82 },
  { name: "DeepSeek", slug: "deepseek", tagline: "Powerful open-source language model", description: "DeepSeek is a powerful open-source LLM that rivals proprietary models in performance.", websiteUrl: "https://deepseek.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=deepseek.com&sz=64", cats: ["chat-ai", "open-source"], isOpenSource: true, score: 85 },
  { name: "Mistral Chat", slug: "mistral-chat", tagline: "Efficient and capable open-weight chatbot", description: "Mistral AI offers state-of-the-art open-weight chat models known for efficiency.", websiteUrl: "https://chat.mistral.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=mistral.ai&sz=64", cats: ["chat-ai", "open-source"], isOpenSource: true, score: 80 },
  { name: "Qwen", slug: "qwen", tagline: "Alibaba's comprehensive AI model family", description: "Qwen is a family of large language models by Alibaba Cloud with strong multilingual capabilities.", websiteUrl: "https://qwen.aliyun.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=qwen.aliyun.com&sz=64", cats: ["chat-ai", "open-source"], isOpenSource: true, score: 78 },
  { name: "Llama 3", slug: "llama-3", tagline: "Meta's most capable open-source LLM", description: "Llama 3 is Meta's latest open-source LLM available in 8B and 70B parameter sizes.", websiteUrl: "https://llama.meta.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=meta.com&sz=64", cats: ["chat-ai", "llms", "open-source"], isOpenSource: true, score: 92 },
  { name: "Mixtral", slug: "mixtral", tagline: "Mistral's mixture of experts model", description: "Mixtral 8x7B uses a mixture of experts architecture for efficient high-quality responses.", websiteUrl: "https://mistral.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=mistral.ai&sz=64", cats: ["chat-ai", "llms", "open-source"], isOpenSource: true, score: 84 },
  { name: "Pi AI", slug: "pi-ai", tagline: "Personal AI assistant by Inflection", description: "Pi is a personal AI assistant designed to be supportive, insightful, and conversational.", websiteUrl: "https://pi.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=pi.ai&sz=64", cats: ["chat-ai"], score: 72 },
  { name: "Kimi", slug: "kimi", tagline: "Long-context AI assistant by Moonshot AI", description: "Kimi supports extremely long context windows for deep document analysis.", websiteUrl: "https://kimi.moonshot.cn", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=kimi.moonshot.cn&sz=64", cats: ["chat-ai"], score: 70 },
  { name: "You.com", slug: "you-com", tagline: "AI search engine with chat capabilities", description: "You.com combines web search with AI chat for comprehensive answers.", websiteUrl: "https://you.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=you.com&sz=64", cats: ["chat-ai"], score: 68 },
  { name: "Poe", slug: "poe", tagline: "Access multiple AI models in one place", description: "Poe by Quora lets you chat with ChatGPT, Claude, Gemini, and more in one interface.", websiteUrl: "https://poe.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=poe.com&sz=64", cats: ["chat-ai"], score: 75 },
  { name: "Character AI", slug: "character-ai", tagline: "AI-powered character conversations", description: "Character AI lets you chat with AI versions of historical figures, fictional characters, and custom personas.", websiteUrl: "https://character.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=character.ai&sz=64", cats: ["chat-ai"], score: 74 },
  { name: "HuggingChat", slug: "hugging-chat", tagline: "Open-source AI chat interface", description: "HuggingChat is a free open-source chat interface powered by various LLMs.", websiteUrl: "https://huggingface.co/chat", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=huggingface.co&sz=64", cats: ["chat-ai", "open-source"], isOpenSource: true, score: 73 },
  { name: "Le Chat", slug: "le-chat", tagline: "Mistral AI's conversational agent", description: "Le Chat is Mistral AI's free conversational agent with web search capabilities.", websiteUrl: "https://chat.mistral.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=mistral.ai&sz=64", cats: ["chat-ai"], score: 65 },
  { name: "Cohere Chat", slug: "cohere-chat", tagline: "Enterprise-focused AI chat platform", description: "Cohere provides enterprise-grade AI chat with retrieval-augmented generation.", websiteUrl: "https://cohere.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=cohere.com&sz=64", cats: ["chat-ai"], score: 70 },
  { name: "Command R", slug: "command-r", tagline: "Cohere's retrieval-augmented model", description: "Command R is optimized for RAG workflows and business applications.", websiteUrl: "https://cohere.com/command", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=cohere.com&sz=64", cats: ["chat-ai", "open-source"], isOpenSource: true, score: 72 },
  { name: "Dolphin 3", slug: "dolphin-3", tagline: "Uncensored open-source LLM", description: "Dolphin 3 is an open-source uncensored LLM fine-tuned for instruction following.", websiteUrl: "https://huggingface.co/cognitivecomputations", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=huggingface.co&sz=64", cats: ["chat-ai", "open-source"], isOpenSource: true, score: 66 },
  { name: "Phi-4", slug: "phi-4", tagline: "Microsoft's efficient small language model", description: "Phi-4 by Microsoft delivers strong performance in a compact, efficient model.", websiteUrl: "https://azure.microsoft.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=microsoft.com&sz=64", cats: ["chat-ai", "open-source"], isOpenSource: true, score: 76 },

  // === CODING (20+) ===
  { name: "GitHub Copilot", slug: "github-copilot", tagline: "AI pair programmer for faster coding", description: "Real-time code suggestions in your IDE.", websiteUrl: "https://github.com/features/copilot", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=github.com&sz=64", cats: ["coding"], isFeatured: true, score: 98 },
  { name: "Cursor", slug: "cursor", tagline: "AI-first code editor", description: "Cursor is an AI-native IDE built on VS Code with deep AI integration.", websiteUrl: "https://cursor.sh", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=cursor.sh&sz=64", cats: ["coding"], score: 92 },
  { name: "Windsurf", slug: "windsurf", tagline: "Agentic IDE by Codeium", description: "Windsurf is an AI-powered IDE with autonomous coding agent capabilities.", websiteUrl: "https://codeium.com/windsurf", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=codeium.com&sz=64", cats: ["coding"], score: 88 },
  { name: "Tabnine", slug: "tabnine", tagline: "AI code completion for teams", description: "Tabnine provides personalized AI code completions trained on your codebase.", websiteUrl: "https://tabnine.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=tabnine.com&sz=64", cats: ["coding"], score: 78 },
  { name: "Codeium", slug: "codeium", tagline: "Free AI code acceleration platform", description: "Codeium offers free AI code completion, search, and chat for developers.", websiteUrl: "https://codeium.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=codeium.com&sz=64", cats: ["coding"], score: 82 },
  { name: "Amazon Q Developer", slug: "amazon-q", tagline: "AWS-powered AI coding assistant", description: "Amazon Q Developer helps build, deploy, and troubleshoot applications on AWS.", websiteUrl: "https://aws.amazon.com/q", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=aws.amazon.com&sz=64", cats: ["coding"], score: 80 },
  { name: "Replit AI", slug: "replit-ai", tagline: "AI-powered cloud IDE", description: "Replit's AI helps you build and deploy apps directly in the browser.", websiteUrl: "https://replit.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=replit.com&sz=64", cats: ["coding"], score: 83 },
  { name: "Sourcegraph Cody", slug: "cody", tagline: "AI coding assistant for your codebase", description: "Cody understands your entire codebase and provides context-aware AI help.", websiteUrl: "https://sourcegraph.com/cody", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=sourcegraph.com&sz=64", cats: ["coding", "open-source"], isOpenSource: true, score: 76 },
  { name: "Continue", slug: "continue", tagline: "Open-source AI code assistant", description: "Continue is an open-source AI code assistant that integrates with your IDE.", websiteUrl: "https://continue.dev", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=continue.dev&sz=64", cats: ["coding", "open-source"], isOpenSource: true, score: 79 },
  { name: "OpenAI Codex CLI", slug: "openai-codex-cli", tagline: "OpenAI's command-line coding tool", description: "Codex CLI lets you prototype and build applications from the terminal using AI.", websiteUrl: "https://openai.com/codex", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=openai.com&sz=64", cats: ["coding", "open-source"], isOpenSource: true, score: 77 },
  { name: "Aider", slug: "aider", tagline: "AI pair programming in the terminal", description: "Aider is an open-source AI coding assistant that works directly with git repos.", websiteUrl: "https://aider.chat", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=aider.chat&sz=64", cats: ["coding", "open-source"], isOpenSource: true, score: 85 },
  { name: "Cline", slug: "cline", tagline: "Autonomous coding agent for VS Code", description: "Cline is an AI coding agent that can create, edit, and manage your entire codebase.", websiteUrl: "https://cline.bot", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=cline.bot&sz=64", cats: ["coding", "open-source"], isOpenSource: true, score: 84 },
  { name: "CopilotKit", slug: "copilotkit", tagline: "AI copilot framework for React apps", description: "CopilotKit helps you build deeply integrated AI copilots into React applications.", websiteUrl: "https://copilotkit.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=copilotkit.ai&sz=64", cats: ["coding", "open-source"], isOpenSource: true, score: 72 },
  { name: "OpenHands", slug: "openhands", tagline: "AI software development platform", description: "OpenHands is an open-source platform for AI-powered software development agents.", websiteUrl: "https://openhands.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=openhands.ai&sz=64", cats: ["coding", "open-source", "ai-agents"], isOpenSource: true, score: 80 },
  { name: "Sweep AI", slug: "sweep-ai", tagline: "AI that turns bug reports into PRs", description: "Sweep AI automatically turns bug reports and feature requests into pull requests.", websiteUrl: "https://sweep.dev", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=sweep.dev&sz=64", cats: ["coding"], score: 74 },
  { name: "v0 by Vercel", slug: "v0", tagline: "AI-powered UI generation", description: "v0 generates React components and UI from text descriptions.", websiteUrl: "https://v0.dev", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=v0.dev&sz=64", cats: ["coding"], score: 86 },
  { name: "Bolt.new", slug: "bolt-new", tagline: "Full-stack web app AI builder", description: "Bolt.new lets you build, deploy, and iterate on full-stack web apps using AI.", websiteUrl: "https://bolt.new", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=bolt.new&sz=64", cats: ["coding"], score: 81 },
  { name: "Lovable", slug: "lovable", tagline: "Build web apps with natural language", description: "Lovable turns your ideas into full-stack web applications using only natural language.", websiteUrl: "https://lovable.dev", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=lovable.dev&sz=64", cats: ["coding"], score: 79 },
  { name: "Claude Code", slug: "claude-code", tagline: "Anthropic's coding agent", description: "Claude Code is an agentic coding tool from Anthropic for the terminal.", websiteUrl: "https://docs.anthropic.com/claude-code", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=anthropic.com&sz=64", cats: ["coding"], score: 87 },
  { name: "Gemini Code Assist", slug: "gemini-code-assist", tagline: "Google's AI coding companion", description: "Gemini Code Assist offers AI-powered code completion and chat in your IDE.", websiteUrl: "https://cloud.google.com/gemini-code-assist", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=cloud.google.com&sz=64", cats: ["coding"], score: 78 },
  { name: "Supermaven", slug: "supermaven", tagline: "Fast AI code completion", description: "Supermaven offers blazingly fast AI code completions with large context windows.", websiteUrl: "https://supermaven.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=supermaven.com&sz=64", cats: ["coding"], score: 73 },
  { name: "Qodo (Codium)", slug: "qodo", tagline: "AI code quality platform", description: "Qodo generates tests, reviews code, and ensures code quality with AI.", websiteUrl: "https://qodo.ai", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=qodo.ai&sz=64", cats: ["coding"], score: 71 },
  { name: "CodeRabbit", slug: "coderabbit", tagline: "AI-powered code review", description: "CodeRabbit automates code reviews with contextual AI feedback on every PR.", websiteUrl: "https://coderabbit.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=coderabbit.ai&sz=64", cats: ["coding"], score: 75 },
  { name: "Mintlify", slug: "mintlify", tagline: "AI documentation writer", description: "Mintlify helps you write beautiful documentation with AI-powered editing.", websiteUrl: "https://mintlify.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=mintlify.com&sz=64", cats: ["coding"], score: 69 },

  // === IMAGE (20+) ===
  { name: "Midjourney", slug: "midjourney", tagline: "Best-in-class AI image generation", description: "Midjourney creates stunning artistic images from text descriptions.", websiteUrl: "https://midjourney.com", pricing: "PAID", cats: ["image"], isFeatured: true, score: 97 },
  { name: "DALL-E 3", slug: "dalle-3", tagline: "OpenAI's advanced image generator", description: "DALL-E 3 creates highly detailed images from text prompts.", websiteUrl: "https://openai.com/dall-e-3", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=openai.com&sz=64", cats: ["image"], score: 93 },
  { name: "Stable Diffusion", slug: "stable-diffusion", tagline: "Open-source image generation model", description: "Stable Diffusion is a free, open-source text-to-image AI model.", websiteUrl: "https://stability.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=stability.ai&sz=64", cats: ["image", "open-source"], isOpenSource: true, score: 91 },
  { name: "Stable Diffusion 3", slug: "stable-diffusion-3", tagline: "Latest open-source image model", description: "SD3 offers improved prompt adherence and image quality.", websiteUrl: "https://stability.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=stability.ai&sz=64", cats: ["image", "open-source"], isOpenSource: true, score: 88 },
  { name: "Flux", slug: "flux", tagline: "Black Forest Labs' image generation model", description: "Flux by Black Forest Labs delivers exceptional image generation quality.", websiteUrl: "https://blackforestlabs.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=blackforestlabs.ai&sz=64", cats: ["image", "open-source"], isOpenSource: true, score: 90 },
  { name: "Adobe Firefly", slug: "adobe-firefly", tagline: "Adobe's generative AI for images", description: "Firefly integrates AI image generation into Adobe's creative suite.", websiteUrl: "https://firefly.adobe.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=adobe.com&sz=64", cats: ["image"], score: 86 },
  { name: "Canva AI", slug: "canva-ai", tagline: "AI-powered design platform", description: "Canva's AI tools include image generation, background removal, and magic editing.", websiteUrl: "https://canva.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=canva.com&sz=64", cats: ["image"], score: 85 },
  { name: "Leonardo AI", slug: "leonardo-ai", tagline: "AI image generation platform", description: "Leonardo AI offers powerful image generation with fine-tuned community models.", websiteUrl: "https://leonardo.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=leonardo.ai&sz=64", cats: ["image"], score: 82 },
  { name: "Ideogram", slug: "ideogram", tagline: "AI image generation with great typography", description: "Ideogram excels at generating images with accurate text rendering.", websiteUrl: "https://ideogram.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=ideogram.ai&sz=64", cats: ["image"], score: 80 },
  { name: "Playground AI", slug: "playground-ai", tagline: "Free AI image generator", description: "Playground AI offers free AI image generation with easy-to-use interface.", websiteUrl: "https://playgroundai.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=playgroundai.com&sz=64", cats: ["image"], score: 76 },
  { name: "Clipdrop", slug: "clipdrop", tagline: "AI image editing tools suite", description: "Clipdrop offers AI-powered image cleanup, relight, and generation tools.", websiteUrl: "https://clipdrop.co", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=clipdrop.co&sz=64", cats: ["image"], score: 72 },
  { name: "ComfyUI", slug: "comfyui", tagline: "Powerful Stable Diffusion interface", description: "ComfyUI is a node-based interface for Stable Diffusion workflows.", websiteUrl: "https://comfyui.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=comfyui.com&sz=64", cats: ["image", "open-source"], isOpenSource: true, score: 83 },
  { name: "Automatic1111", slug: "automatic1111", tagline: "Stable Diffusion web UI", description: "A1111 is the most popular open-source web interface for Stable Diffusion.", websiteUrl: "https://github.com/AUTOMATIC1111/stable-diffusion-webui", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=github.com&sz=64", cats: ["image", "open-source"], isOpenSource: true, score: 84 },
  { name: "Fooocus", slug: "fooocus", tagline: "User-friendly SD interface", description: "Fooocus is an easy-to-use image generation tool based on Stable Diffusion.", websiteUrl: "https://github.com/lllyasviel/Fooocus", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=github.com&sz=64", cats: ["image", "open-source"], isOpenSource: true, score: 77 },
  { name: "Krea AI", slug: "krea-ai", tagline: "Real-time AI image generation", description: "Krea AI offers real-time AI image generation and video enhancement.", websiteUrl: "https://krea.ai", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=krea.ai&sz=64", cats: ["image"], score: 74 },
  { name: "Magnific AI", slug: "magnific-ai", tagline: "AI image upscaler and enhancer", description: "Magnific AI upscales and enhances images with incredible detail and quality.", websiteUrl: "https://magnific.ai", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=magnific.ai&sz=64", cats: ["image"], score: 75 },
  { name: "Runway Gen-3", slug: "runway-gen3", tagline: "AI image and video generation", description: "Runway's Gen-3 creates both images and videos from text prompts.", websiteUrl: "https://runwayml.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=runwayml.com&sz=64", cats: ["image", "video"], score: 87 },
  { name: "Pika Art", slug: "pika-art", tagline: "AI video and image creation", description: "Pika lets you create and edit videos and images with simple text prompts.", websiteUrl: "https://pika.art", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=pika.art&sz=64", cats: ["image", "video"], score: 81 },
  { name: "Recraft AI", slug: "recraft-ai", tagline: "AI design and illustration tool", description: "Recraft creates vector illustrations, icons, and brand-consistent designs.", websiteUrl: "https://recraft.ai", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=recraft.ai&sz=64", cats: ["image"], score: 71 },
  { name: "Stability AI API", slug: "stability-ai-api", tagline: "Stability AI's developer API", description: "Access Stable Diffusion models via Stability AI's developer API.", websiteUrl: "https://platform.stability.ai", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=stability.ai&sz=64", cats: ["image"], score: 79 },

  // === VIDEO (20+) ===
  { name: "Runway Gen-3", slug: "runway-gen3-video", tagline: "AI video generation and editing", description: "Runway's Gen-3 Alpha creates high-quality videos from text, images, or video inputs.", websiteUrl: "https://runwayml.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=runwayml.com&sz=64", cats: ["video"], score: 92 },
  { name: "Pika", slug: "pika", tagline: "AI video creation platform", description: "Pika lets anyone create and edit videos with simple text prompts.", websiteUrl: "https://pika.art", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=pika.art&sz=64", cats: ["video"], score: 88 },
  { name: "Sora", slug: "sora", tagline: "OpenAI's video generation model", description: "Sora creates realistic and imaginative videos from text descriptions.", websiteUrl: "https://sora.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=sora.com&sz=64", cats: ["video"], isFeatured: true, score: 95 },
  { name: "Synthesia", slug: "synthesia", tagline: "AI video creation with avatars", description: "Synthesia creates professional videos with AI avatars from text scripts.", websiteUrl: "https://synthesia.io", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=synthesia.io&sz=64", cats: ["video"], score: 86 },
  { name: "HeyGen", slug: "heygen", tagline: "AI video generation with real avatars", description: "HeyGen creates realistic AI avatar videos from text or audio input.", websiteUrl: "https://heygen.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=heygen.com&sz=64", cats: ["video"], score: 85 },
  { name: "CapCut", slug: "capcut", tagline: "Free video editor with AI features", description: "CapCut offers AI-powered video editing, text-to-speech, and effects.", websiteUrl: "https://capcut.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=capcut.com&sz=64", cats: ["video"], score: 80 },
  { name: "Kaiber", slug: "kaiber", tagline: "AI video generation for creators", description: "Kaiber transforms images and text into stunning animated videos.", websiteUrl: "https://kaiber.ai", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=kaiber.ai&sz=64", cats: ["video"], score: 78 },
  { name: "Veed.io", slug: "veed-io", tagline: "Online video editor with AI", description: "Veed.io offers AI subtitles, translation, and video editing in the browser.", websiteUrl: "https://veed.io", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=veed.io&sz=64", cats: ["video"], score: 74 },
  { name: "Descript", slug: "descript", tagline: "AI-powered video and audio editor", description: "Descript lets you edit video by editing the transcript text.", websiteUrl: "https://descript.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=descript.com&sz=64", cats: ["video"], score: 82 },
  { name: "Invideo AI", slug: "invideo-ai", tagline: "AI video creator for marketing", description: "Invideo AI generates complete videos from text prompts with voiceover and stock footage.", websiteUrl: "https://invideo.io", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=invideo.io&sz=64", cats: ["video", "marketing"], score: 79 },
  { name: "Pictory", slug: "pictory", tagline: "AI video creation from scripts", description: "Pictory turns blog posts and scripts into engaging videos automatically.", websiteUrl: "https://pictory.ai", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=pictory.ai&sz=64", cats: ["video", "marketing"], score: 73 },
  { name: "Fliki", slug: "fliki", tagline: "Text-to-video with AI voices", description: "Fliki converts blog posts and text into videos with realistic AI voiceovers.", websiteUrl: "https://fliki.ai", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=fliki.ai&sz=64", cats: ["video"], score: 71 },
  { name: "ElevenLabs", slug: "elevenlabs", tagline: "AI voice and video dubbing", description: "ElevenLabs offers voice cloning, text-to-speech, and AI video dubbing.", websiteUrl: "https://elevenlabs.io", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=elevenlabs.io&sz=64", cats: ["video", "voice"], score: 90 },
  { name: "Wisecut", slug: "wisecut", tagline: "AI video editor for content creators", description: "Wisecut uses AI to auto-edit videos, add subtitles, and remove silences.", websiteUrl: "https://wisecut.video", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=wisecut.video&sz=64", cats: ["video"], score: 68 },

  // === VOICE (20+) ===
  { name: "ElevenLabs", slug: "elevenlabs-voice", tagline: "Premium AI voice generation", description: "ElevenLabs offers the most realistic AI text-to-speech and voice cloning.", websiteUrl: "https://elevenlabs.io", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=elevenlabs.io&sz=64", cats: ["voice"], isFeatured: true, score: 94 },
  { name: "Whisper", slug: "whisper", tagline: "OpenAI's speech recognition system", description: "Whisper is OpenAI's open-source speech-to-text model with multilingual support.", websiteUrl: "https://openai.com/research/whisper", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=openai.com&sz=64", cats: ["voice", "open-source"], isOpenSource: true, score: 92 },
  { name: "Murf AI", slug: "murf-ai", tagline: "AI voice generator for professionals", description: "Murf AI creates studio-quality voiceovers with natural-sounding AI voices.", websiteUrl: "https://murf.ai", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=murf.ai&sz=64", cats: ["voice"], score: 82 },
  { name: "Play.ht", slug: "play-ht", tagline: "AI text-to-speech platform", description: "Play.ht offers realistic AI voice generation with voice cloning capabilities.", websiteUrl: "https://play.ht", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=play.ht&sz=64", cats: ["voice"], score: 78 },
  { name: "Resemble AI", slug: "resemble-ai", tagline: "AI voice cloning and generation", description: "Resemble AI creates custom AI voices and offers real-time voice cloning.", websiteUrl: "https://resemble.ai", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=resemble.ai&sz=64", cats: ["voice"], score: 76 },
  { name: "Speechify", slug: "speechify", tagline: "AI text-to-speech reader", description: "Speechify converts any text into natural-sounding audio with AI voices.", websiteUrl: "https://speechify.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=speechify.com&sz=64", cats: ["voice"], score: 80 },
  { name: "WellSaid", slug: "wellsaid", tagline: "AI voice for enterprise", description: "WellSaid Labs creates enterprise-grade AI voiceovers for training and content.", websiteUrl: "https://wellsaidlabs.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=wellsaidlabs.com&sz=64", cats: ["voice"], score: 74 },
  { name: "Listnr", slug: "listnr", tagline: "AI text-to-speech with emotions", description: "Listnr generates AI voiceovers with emotional range and multiple languages.", websiteUrl: "https://listnr.ai", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=listnr.ai&sz=64", cats: ["voice"], score: 70 },
  { name: "Vocloner", slug: "vocloner", tagline: "Open-source voice cloning", description: "Vocloner is an open-source voice cloning tool for creating custom AI voices.", websiteUrl: "https://github.com/vocloner", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=github.com&sz=64", cats: ["voice", "open-source"], isOpenSource: true, score: 65 },
  { name: "Bark", slug: "bark", tagline: "Suno's text-to-audio model", description: "Bark generates realistic speech, music, and sound effects from text.", websiteUrl: "https://github.com/suno-ai/bark", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=github.com&sz=64", cats: ["voice", "open-source"], isOpenSource: true, score: 77 },
  { name: "Coqui TTS", slug: "coqui-tts", tagline: "Open-source text-to-speech", description: "Coqui TTS is a free, open-source text-to-speech engine with many language models.", websiteUrl: "https://github.com/coqui-ai/TTS", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=github.com&sz=64", cats: ["voice", "open-source"], isOpenSource: true, score: 72 },
  { name: "Azure Speech", slug: "azure-speech", tagline: "Microsoft's speech services", description: "Azure Speech offers speech-to-text, text-to-speech, translation, and customization.", websiteUrl: "https://azure.microsoft.com/speech", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=microsoft.com&sz=64", cats: ["voice"], score: 85 },
  { name: "Google Cloud TTS", slug: "google-tts", tagline: "Google's text-to-speech API", description: "Google Cloud TTS offers 300+ voices across 60+ languages with WaveNet technology.", websiteUrl: "https://cloud.google.com/text-to-speech", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=cloud.google.com&sz=64", cats: ["voice"], score: 83 },
  { name: "Amazon Polly", slug: "amazon-polly", tagline: "AWS text-to-speech service", description: "Amazon Polly turns text into lifelike speech using deep learning.", websiteUrl: "https://aws.amazon.com/polly", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=aws.amazon.com&sz=64", cats: ["voice"], score: 79 },
  { name: "RVC", slug: "rvc", tagline: "Real-time voice cloning", description: "RVC (Retrieval-based Voice Conversion) is an open-source real-time voice cloning tool.", websiteUrl: "https://github.com/RVC-Project", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=github.com&sz=64", cats: ["voice", "open-source"], isOpenSource: true, score: 73 },
  { name: "Voicebox", slug: "voicebox", tagline: "Meta's generative voice model", description: "Voicebox by Meta generates speech across six languages with style transfer.", websiteUrl: "https://voicebox.meta.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=meta.com&sz=64", cats: ["voice", "open-source"], isOpenSource: true, score: 75 },
  { name: "Fish Speech", slug: "fish-speech", tagline: "Open-source text-to-speech", description: "Fish Speech is an open-source multilingual TTS model with voice cloning.", websiteUrl: "https://fish.audio", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=fish.audio&sz=64", cats: ["voice", "open-source"], isOpenSource: true, score: 71 },
  { name: "LMNT", slug: "lmnt", tagline: "Expressive AI voice generation", description: "LMNT creates emotionally expressive AI voices with fine-grained control.", websiteUrl: "https://lmnt.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=lmnt.com&sz=64", cats: ["voice"], score: 69 },

  // === MARKETING (20+) ===
  { name: "HubSpot AI", slug: "hubspot-ai", tagline: "AI-powered marketing platform", description: "HubSpot's AI tools include content generation, SEO, analytics, and automation.", websiteUrl: "https://hubspot.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=hubspot.com&sz=64", cats: ["marketing"], score: 88 },
  { name: "Jasper", slug: "jasper", tagline: "AI marketing copywriting", description: "Jasper generates marketing copy, blog posts, ad copy, and social media content.", websiteUrl: "https://jasper.ai", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=jasper.ai&sz=64", cats: ["marketing", "writing"], score: 86 },
  { name: "Copy.ai", slug: "copy-ai", tagline: "AI copywriting for marketing", description: "Copy.ai creates marketing copy, emails, ads, and social media content with AI.", websiteUrl: "https://copy.ai", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=copy.ai&sz=64", cats: ["marketing", "writing"], score: 82 },
  { name: "Writesonic", slug: "writesonic", tagline: "AI content creation for marketing", description: "Writesonic generates SEO-optimized content, ads, emails, and landing pages.", websiteUrl: "https://writesonic.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=writesonic.com&sz=64", cats: ["marketing", "writing"], score: 80 },
  { name: "Surfer SEO", slug: "surfer-seo", tagline: "AI-powered SEO optimization", description: "Surfer SEO analyzes and optimizes content for better search engine rankings.", websiteUrl: "https://surferseo.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=surferseo.com&sz=64", cats: ["marketing"], score: 84 },
  { name: "Semrush AI", slug: "semrush-ai", tagline: "AI SEO and marketing toolkit", description: "Semrush offers AI-powered keyword research, content optimization, and competitor analysis.", websiteUrl: "https://semrush.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=semrush.com&sz=64", cats: ["marketing"], score: 88 },
  { name: "Ahrefs", slug: "ahrefs", tagline: "SEO and backlink analysis tool", description: "Ahrefs helps marketers analyze backlinks, keywords, and competitor strategies.", websiteUrl: "https://ahrefs.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=ahrefs.com&sz=64", cats: ["marketing"], score: 87 },
  { name: "Mailchimp AI", slug: "mailchimp-ai", tagline: "AI email marketing platform", description: "Mailchimp's AI helps design emails, optimize send times, and segment audiences.", websiteUrl: "https://mailchimp.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=mailchimp.com&sz=64", cats: ["marketing"], score: 81 },
  { name: "AdCreative AI", slug: "adcreative-ai", tagline: "AI ad creative generation", description: "AdCreative.ai generates high-converting ad creatives and social media visuals.", websiteUrl: "https://adcreative.ai", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=adcreative.ai&sz=64", cats: ["marketing"], score: 76 },
  { name: "Phrasee", slug: "phrasee", tagline: "AI marketing language optimization", description: "Phrasee optimizes marketing copy language for email, push, and SMS campaigns.", websiteUrl: "https://phrasee.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=phrasee.com&sz=64", cats: ["marketing"], score: 74 },
  { name: "Crystal AI", slug: "crystal-ai", tagline: "AI personality insights for sales", description: "Crystal uses AI to analyze personalities and improve sales communications.", websiteUrl: "https://crystalknows.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=crystalknows.com&sz=64", cats: ["marketing", "business"], score: 68 },
  { name: "Mutiny", slug: "mutiny", tagline: "AI website personalization", description: "Mutiny personalizes website content for each visitor using AI.", websiteUrl: "https://mutiny.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=mutiny.com&sz=64", cats: ["marketing"], score: 72 },
  { name: "Seventh Sense", slug: "seventh-sense", tagline: "AI email send time optimization", description: "Seventh Sense optimizes email send times for maximum engagement using AI.", websiteUrl: "https://seventhsense.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=seventhsense.com&sz=64", cats: ["marketing"], score: 66 },

  // === WRITING (20+) ===
  { name: "Jasper", slug: "jasper-writing", tagline: "AI content writing platform", description: "Jasper helps teams create on-brand content 10x faster with AI.", websiteUrl: "https://jasper.ai", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=jasper.ai&sz=64", cats: ["writing"], isFeatured: true, score: 91 },
  { name: "Copy.ai", slug: "copy-ai-writing", tagline: "AI writing for business", description: "Copy.ai generates marketing copy, blog posts, and social media content.", websiteUrl: "https://copy.ai", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=copy.ai&sz=64", cats: ["writing"], score: 84 },
  { name: "Writesonic", slug: "writesonic-writing", tagline: "AI writing assistant", description: "Writesonic creates SEO content, articles, ads, and product descriptions.", websiteUrl: "https://writesonic.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=writesonic.com&sz=64", cats: ["writing"], score: 82 },
  { name: "Grammarly", slug: "grammarly", tagline: "AI writing and grammar assistant", description: "Grammarly checks grammar, tone, clarity, and engagement in real-time.", websiteUrl: "https://grammarly.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=grammarly.com&sz=64", cats: ["writing"], isFeatured: true, score: 93 },
  { name: "ProWritingAid", slug: "prowritingaid", tagline: "AI writing coach and editor", description: "ProWritingAid offers comprehensive writing analysis and improvement suggestions.", websiteUrl: "https://prowritingaid.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=prowritingaid.com&sz=64", cats: ["writing"], score: 83 },
  { name: "Hemingway Editor", slug: "hemingway", tagline: "AI writing clarity tool", description: "Hemingway Editor makes your writing bold and clear by highlighting complex sentences.", websiteUrl: "https://hemingwayapp.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=hemingwayapp.com&sz=64", cats: ["writing"], score: 76 },
  { name: "Notion AI", slug: "notion-ai", tagline: "AI writing in your workspace", description: "Notion AI helps you write, brainstorm, edit, and summarize directly in your docs.", websiteUrl: "https://notion.so", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=notion.so&sz=64", cats: ["writing", "productivity"], score: 89 },
  { name: "Sudowrite", slug: "sudowrite", tagline: "AI writing for fiction and creative", description: "Sudowrite helps creative writers with brainstorming, rewriting, and story development.", websiteUrl: "https://sudowrite.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=sudowrite.com&sz=64", cats: ["writing"], score: 81 },
  { name: "Rytr", slug: "rytr", tagline: "Affordable AI writing assistant", description: "Rytr generates high-quality content at an affordable price for small businesses.", websiteUrl: "https://rytr.me", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=rytr.me&sz=64", cats: ["writing"], score: 77 },
  { name: "QuillBot", slug: "quillbot", tagline: "AI paraphrasing and writing tool", description: "QuillBot helps paraphrase, summarize, and improve your writing.", websiteUrl: "https://quillbot.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=quillbot.com&sz=64", cats: ["writing"], score: 80 },
  { name: "ChatGPT Writer", slug: "chatgpt-writer", tagline: "AI writing extension for browsers", description: "ChatGPT Writer uses AI to compose emails, replies, and messages in any browser.", websiteUrl: "https://chatgptwriter.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=chatgptwriter.ai&sz=64", cats: ["writing"], score: 72 },
  { name: "Writer AI", slug: "writer-ai", tagline: "Enterprise AI writing platform", description: "Writer offers enterprise-grade AI writing with brand voice customization.", websiteUrl: "https://writer.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=writer.com&sz=64", cats: ["writing"], score: 79 },
  { name: "Lex", slug: "lex", tagline: "AI-powered word processor", description: "Lex is a modern word processor with built-in AI writing assistance.", websiteUrl: "https://lex.page", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=lex.page&sz=64", cats: ["writing"], score: 71 },
  { name: "Draft", slug: "draft-ai", tagline: "AI document collaboration", description: "Draft uses AI to help teams write, edit, and collaborate on documents faster.", websiteUrl: "https://draft.ai", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=draft.ai&sz=64", cats: ["writing"], score: 67 },

  // === PRODUCTIVITY (20+) ===
  { name: "Notion AI", slug: "notion-ai-prod", tagline: "AI-powered productivity workspace", description: "Notion combines docs, wikis, and projects with AI assistance.", websiteUrl: "https://notion.so", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=notion.so&sz=64", cats: ["productivity"], isFeatured: true, score: 94 },
  { name: "Motion", slug: "motion", tagline: "AI calendar and project manager", description: "Motion automatically schedules your tasks and projects using AI.", websiteUrl: "https://usemotion.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=usemotion.com&sz=64", cats: ["productivity"], score: 85 },
  { name: "Mem AI", slug: "mem-ai", tagline: "AI knowledge organizer", description: "Mem organizes your notes and knowledge with AI-powered search and suggestions.", websiteUrl: "https://mem.ai", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=mem.ai&sz=64", cats: ["productivity"], score: 80 },
  { name: "Otter AI", slug: "otter-ai", tagline: "AI meeting assistant", description: "Otter records, transcribes, and summarizes meetings in real-time.", websiteUrl: "https://otter.ai", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=otter.ai&sz=64", cats: ["productivity"], score: 86 },
  { name: "Fireflies AI", slug: "fireflies-ai", tagline: "AI meeting transcription and notes", description: "Fireflies automatically records, transcribes, and analyzes meeting conversations.", websiteUrl: "https://fireflies.ai", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=fireflies.ai&sz=64", cats: ["productivity"], score: 82 },
  { name: "Reclaim AI", slug: "reclaim-ai", tagline: "AI calendar scheduling", description: "Reclaim optimizes your calendar, schedules tasks, and protects focus time.", websiteUrl: "https://reclaim.ai", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=reclaim.ai&sz=64", cats: ["productivity"], score: 78 },
  { name: "Taskade", slug: "taskade", tagline: "AI workspace for teams", description: "Taskade combines tasks, notes, and AI into one collaborative workspace.", websiteUrl: "https://taskade.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=taskade.com&sz=64", cats: ["productivity"], score: 75 },
  { name: "Todoist AI", slug: "todoist-ai", tagline: "AI-enhanced task management", description: "Todoist uses AI to suggest tasks, prioritize work, and organize projects.", websiteUrl: "https://todoist.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=todoist.com&sz=64", cats: ["productivity"], score: 83 },
  { name: "ClickUp AI", slug: "clickup-ai", tagline: "AI project management platform", description: "ClickUp offers AI-powered project management, docs, goals, and chat.", websiteUrl: "https://clickup.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=clickup.com&sz=64", cats: ["productivity", "business"], score: 87 },
  { name: "Superhuman", slug: "superhuman", tagline: "AI email client", description: "Superhuman is the fastest email experience with AI-powered sorting and replies.", websiteUrl: "https://superhuman.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=superhuman.com&sz=64", cats: ["productivity"], score: 84 },
  { name: "Raycast AI", slug: "raycast-ai", tagline: "AI-powered productivity launcher", description: "Raycast replaces your Spotlight with AI-powered commands and workflows.", websiteUrl: "https://raycast.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=raycast.com&sz=64", cats: ["productivity"], score: 88 },
  { name: "Arc Browser", slug: "arc-browser", tagline: "AI browser for organized browsing", description: "Arc is a browser with built-in AI features for tab management and organization.", websiteUrl: "https://arc.net", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=arc.net&sz=64", cats: ["productivity"], score: 79 },
  { name: "Dex AI", slug: "dex-ai", tagline: "AI relationship management", description: "Dex helps you manage relationships with automatic contact enrichment and reminders.", websiteUrl: "https://dex.ai", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=dex.ai&sz=64", cats: ["productivity", "business"], score: 72 },
  { name: "Text Blaze", slug: "text-blaze", tagline: "AI text expander and snippets", description: "Text Blaze saves time with AI-powered text snippets, templates, and automation.", websiteUrl: "https://blaze.today", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=blaze.today&sz=64", cats: ["productivity"], score: 66 },

  // === BUSINESS (20+) ===
  { name: "Gong AI", slug: "gong-ai", tagline: "AI revenue intelligence platform", description: "Gong analyzes sales calls and meetings to provide actionable revenue insights.", websiteUrl: "https://gong.io", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=gong.io&sz=64", cats: ["business"], score: 90 },
  { name: "Clari", slug: "clari", tagline: "AI revenue operations platform", description: "Clari uses AI to forecast revenue, manage pipelines, and align teams.", websiteUrl: "https://clari.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=clari.com&sz=64", cats: ["business"], score: 86 },
  { name: "People AI", slug: "people-ai", tagline: "AI relationship intelligence", description: "People.ai maps team relationships and provides sales intelligence.", websiteUrl: "https://people.ai", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=people.ai&sz=64", cats: ["business"], score: 78 },
  { name: "Copy.ai Workflows", slug: "copy-ai-workflows", tagline: "AI business process automation", description: "Copy.ai Workflows automate business processes with AI-generated content pipelines.", websiteUrl: "https://copy.ai", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=copy.ai&sz=64", cats: ["business", "automation"], score: 74 },
  { name: "Lavender AI", slug: "lavender-ai", tagline: "AI email sales coach", description: "Lavender analyzes and optimizes sales emails for better reply rates.", websiteUrl: "https://lavender.ai", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=lavender.ai&sz=64", cats: ["business", "marketing"], score: 72 },
  { name: "Vanta AI", slug: "vanta-ai", tagline: "AI security and compliance automation", description: "Vanta automates SOC 2, ISO 27001, and other compliance frameworks with AI.", websiteUrl: "https://vanta.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=vanta.com&sz=64", cats: ["business"], score: 82 },
  { name: "Lattice AI", slug: "lattice-ai", tagline: "AI people management platform", description: "Lattice helps manage performance reviews, engagement, and employee growth with AI.", websiteUrl: "https://lattice.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=lattice.com&sz=64", cats: ["business"], score: 80 },
  { name: "Drift AI", slug: "drift-ai", tagline: "AI conversational marketing", description: "Drift uses AI chatbots to qualify leads and book meetings automatically.", websiteUrl: "https://drift.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=drift.com&sz=64", cats: ["business", "marketing"], score: 83 },
  { name: "Clerk AI", slug: "clerk-ai", tagline: "AI for procurement and sourcing", description: "Clerk AI automates procurement workflows and supplier management with AI.", websiteUrl: "https://clerk.ai", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=clerk.ai&sz=64", cats: ["business"], score: 70 },
  { name: "AlphaSense", slug: "alpha-sense", tagline: "AI market intelligence platform", description: "AlphaSense uses AI to search and analyze market data, filings, and research.", websiteUrl: "https://alpha-sense.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=alpha-sense.com&sz=64", cats: ["business"], score: 81 },

  // === EDUCATION (20+) ===
  { name: "Khan Academy AI", slug: "khan-academy-ai", tagline: "AI tutoring for every student", description: "Khan Academy's AI tutor Khanmigo provides personalized learning assistance.", websiteUrl: "https://khanacademy.org", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=khanacademy.org&sz=64", cats: ["education"], isFeatured: true, score: 92 },
  { name: "Duolingo AI", slug: "duolingo-ai", tagline: "AI language learning platform", description: "Duolingo uses AI to personalize language lessons and adapt to each learner.", websiteUrl: "https://duolingo.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=duolingo.com&sz=64", cats: ["education"], score: 90 },
  { name: "Quizlet AI", slug: "quizlet-ai", tagline: "AI-powered study tools", description: "Quizlet's AI generates flashcards, practice tests, and study guides.", websiteUrl: "https://quizlet.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=quizlet.com&sz=64", cats: ["education"], score: 84 },
  { name: "Course Hero AI", slug: "course-hero-ai", tagline: "AI homework help", description: "Course Hero offers AI-powered tutoring, explanations, and homework assistance.", websiteUrl: "https://coursehero.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=coursehero.com&sz=64", cats: ["education"], score: 78 },
  { name: "Brainly AI", slug: "brainly-ai", tagline: "AI learning community", description: "Brainly combines AI with community Q&A for homework help.", websiteUrl: "https://brainly.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=brainly.com&sz=64", cats: ["education"], score: 76 },
  { name: "Photomath", slug: "photomath", tagline: "AI math problem solver", description: "Photomath solves math problems by scanning with your camera.", websiteUrl: "https://photomath.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=photomath.com&sz=64", cats: ["education"], score: 85 },
  { name: "Grammarly Edu", slug: "grammarly-edu", tagline: "AI writing for students", description: "Grammarly helps students improve their academic writing with real-time feedback.", websiteUrl: "https://grammarly.com/edu", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=grammarly.com&sz=64", cats: ["education", "writing"], score: 88 },
  { name: "Coursera AI", slug: "coursera-ai", tagline: "AI-powered online learning", description: "Coursera uses AI to recommend courses and personalize learning paths.", websiteUrl: "https://coursera.org", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=coursera.org&sz=64", cats: ["education"], score: 87 },
  { name: "EdX AI", slug: "edx-ai", tagline: "AI-enhanced university courses", description: "edX offers AI-powered course recommendations and learning analytics.", websiteUrl: "https://edx.org", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=edx.org&sz=64", cats: ["education"], score: 83 },
  { name: "Brilliant AI", slug: "brilliant-ai", tagline: "AI interactive learning platform", description: "Brilliant offers hands-on AI and math learning with interactive challenges.", websiteUrl: "https://brilliant.org", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=brilliant.org&sz=64", cats: ["education"], score: 82 },
  { name: "Memrise AI", slug: "memrise-ai", tagline: "AI language learning with natives", description: "Memrise uses AI to teach languages with native speaker video clips.", websiteUrl: "https://memrise.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=memrise.com&sz=64", cats: ["education"], score: 77 },
  { name: "Socratic", slug: "socratic", tagline: "AI homework helper by Google", description: "Socratic uses AI to explain answers and help students learn step by step.", websiteUrl: "https://socratic.org", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=socratic.org&sz=64", cats: ["education"], score: 79 },
  { name: "Knowt", slug: "knowt", tagline: "AI flashcards and study tools", description: "Knowt turns your notes into AI-powered flashcards and practice tests.", websiteUrl: "https://knowt.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=knowt.com&sz=64", cats: ["education"], score: 71 },
  { name: "Chegg AI", slug: "chegg-ai", tagline: "AI homework and tutoring help", description: "Chegg provides AI-powered homework help, tutoring, and textbook solutions.", websiteUrl: "https://chegg.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=chegg.com&sz=64", cats: ["education"], score: 80 },

  // === AUTOMATION (20+) ===
  { name: "Zapier AI", slug: "zapier-ai", tagline: "AI workflow automation", description: "Zapier connects apps and automates workflows with AI-powered triggers and actions.", websiteUrl: "https://zapier.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=zapier.com&sz=64", cats: ["automation"], isFeatured: true, score: 93 },
  { name: "Make (Integromat)", slug: "make", tagline: "Visual automation platform", description: "Make lets you create complex automations with a visual drag-and-drop interface.", websiteUrl: "https://make.com", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=make.com&sz=64", cats: ["automation"], score: 87 },
  { name: "N8N", slug: "n8n", tagline: "Fair-code workflow automation", description: "N8N is an open-source workflow automation tool with fair-code licensing.", websiteUrl: "https://n8n.io", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=n8n.io&sz=64", cats: ["automation", "open-source"], isOpenSource: true, score: 86 },
  { name: "ActivePieces", slug: "activepieces", tagline: "Open-source automation platform", description: "ActivePieces is an open-source alternative to Zapier with unlimited workflows.", websiteUrl: "https://activepieces.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=activepieces.com&sz=64", cats: ["automation", "open-source"], isOpenSource: true, score: 78 },
  { name: "UiPath", slug: "uipath", tagline: "Enterprise RPA platform", description: "UiPath automates repetitive business processes with AI-powered robots.", websiteUrl: "https://uipath.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=uipath.com&sz=64", cats: ["automation"], score: 88 },
  { name: "Automation Anywhere", slug: "automation-anywhere", tagline: "AI-powered RPA platform", description: "Automation Anywhere combines RPA with AI for intelligent process automation.", websiteUrl: "https://automationanywhere.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=automationanywhere.com&sz=64", cats: ["automation"], score: 85 },
  { name: "Tray.io", slug: "tray-io", tagline: "Embedded integration platform", description: "Tray.io lets you build and embed automated integrations into your products.", websiteUrl: "https://tray.io", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=tray.io&sz=64", cats: ["automation"], score: 76 },
  { name: "Workato", slug: "workato", tagline: "Enterprise automation platform", description: "Workato connects enterprise apps and automates complex business workflows.", websiteUrl: "https://workato.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=workato.com&sz=64", cats: ["automation", "business"], score: 84 },
  { name: "Parabola", slug: "parabola", tagline: "Visual data automation", description: "Parabola automates data processing and ETL workflows with a visual canvas.", websiteUrl: "https://parabola.io", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=parabola.io&sz=64", cats: ["automation"], score: 74 },
  { name: "Zapier Central", slug: "zapier-central", tagline: "AI agent for automation", description: "Zapier Central lets you create AI agents that automate complex workflows.", websiteUrl: "https://zapier.com/central", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=zapier.com&sz=64", cats: ["automation", "ai-agents"], score: 80 },
  { name: "Latenode", slug: "latenode", tagline: "Open-source workflow automation", description: "Latenode is an open-source low-code automation platform with AI capabilities.", websiteUrl: "https://latenode.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=latenode.com&sz=64", cats: ["automation", "open-source"], isOpenSource: true, score: 71 },

  // === OPEN SOURCE (additional beyond existing) ===
  { name: "Ollama", slug: "ollama-os", tagline: "Run LLMs locally with ease", description: "Ollama lets you run Llama 3, Mistral, Gemma, and other models locally.", websiteUrl: "https://ollama.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=ollama.ai&sz=64", cats: ["open-source", "local-ai"], isOpenSource: true, isFeatured: true, score: 95 },
  { name: "LangChain", slug: "langchain-os", tagline: "Build LLM-powered applications", description: "LangChain is a framework for developing applications powered by language models.", websiteUrl: "https://langchain.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=langchain.com&sz=64", cats: ["open-source", "ai-agents"], isOpenSource: true, score: 88 },
  { name: "Hugging Face", slug: "huggingface", tagline: "The AI community's model hub", description: "Hugging Face hosts 500k+ models, datasets, and Spaces for AI.", websiteUrl: "https://huggingface.co", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=huggingface.co&sz=64", cats: ["open-source", "llms"], isOpenSource: true, score: 96 },

  // === LLMs (additional beyond existing) ===
  { name: "GPT-4o", slug: "gpt-4o", tagline: "OpenAI's flagship multimodal model", description: "GPT-4o understands text, images, and audio with human-level reasoning.", websiteUrl: "https://openai.com/gpt-4o", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=openai.com&sz=64", cats: ["llms"], score: 98 },
  { name: "Gemini 2.0", slug: "gemini-2", tagline: "Google's most advanced AI model", description: "Gemini 2.0 is Google's most capable model with multimodal understanding.", websiteUrl: "https://deepmind.google/gemini", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=deepmind.google&sz=64", cats: ["llms"], score: 93 },
  { name: "Claude 3.5", slug: "claude-35", tagline: "Anthropic's most intelligent model", description: "Claude 3.5 Sonnet balances speed and intelligence for complex tasks.", websiteUrl: "https://claude.ai", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=claude.ai&sz=64", cats: ["llms"], score: 94 },
  { name: "Mistral Large", slug: "mistral-large", tagline: "Mistral's top-tier model", description: "Mistral Large offers state-of-the-art reasoning and multilingual capabilities.", websiteUrl: "https://mistral.ai", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=mistral.ai&sz=64", cats: ["llms", "open-source"], isOpenSource: true, score: 86 },
  { name: "DeepSeek R1", slug: "deepseek-r1", tagline: "Open-source reasoning model", description: "DeepSeek R1 is an open-source model with advanced reasoning capabilities.", websiteUrl: "https://deepseek.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=deepseek.com&sz=64", cats: ["llms", "open-source"], isOpenSource: true, score: 89 },

  // === AI AGENTS (additional) ===
  { name: "AutoGPT", slug: "autogpt-agent", tagline: "Autonomous AI agent", description: "AutoGPT accomplishes user-defined goals by breaking them into subtasks.", websiteUrl: "https://agpt.co", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=agpt.co&sz=64", cats: ["ai-agents", "open-source"], isOpenSource: true, score: 84 },
  { name: "CrewAI", slug: "crewai", tagline: "Multi-agent orchestration framework", description: "CrewAI orchestrates role-based AI agents to work together on complex tasks.", websiteUrl: "https://crewai.com", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=crewai.com&sz=64", cats: ["ai-agents", "open-source"], isOpenSource: true, score: 82 },
  { name: "Superagent", slug: "superagent", tagline: "Build AI agents easily", description: "Superagent lets you build, deploy, and manage AI agents without code.", websiteUrl: "https://superagent.sh", pricing: "FREEMIUM", logo: "https://www.google.com/s2/favicons?domain=superagent.sh&sz=64", cats: ["ai-agents"], score: 76 },
  { name: "Microsoft Copilot Studio", slug: "copilot-studio", tagline: "Build custom AI copilots", description: "Microsoft's platform for building custom AI agents and copilots.", websiteUrl: "https://copilotstudio.microsoft.com", pricing: "PAID", logo: "https://www.google.com/s2/favicons?domain=microsoft.com&sz=64", cats: ["ai-agents"], score: 85 },

  // === LOCAL AI (additional) ===
  { name: "LM Studio", slug: "lm-studio-local", tagline: "Run local LLMs with a GUI", description: "LM Studio provides a desktop app for downloading and running local LLMs.", websiteUrl: "https://lmstudio.ai", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=lmstudio.ai&sz=64", cats: ["local-ai", "open-source"], isOpenSource: true, score: 83 },
  { name: "llama.cpp", slug: "llama-cpp-local", tagline: "Run LLMs on CPU", description: "llama.cpp enables running large language models on consumer hardware.", websiteUrl: "https://github.com/ggerganov/llama.cpp", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=github.com&sz=64", cats: ["local-ai", "open-source"], isOpenSource: true, score: 87 },
  { name: "LocalAI", slug: "local-ai", tagline: "Self-hosted OpenAI API alternative", description: "LocalAI provides a local, self-hosted OpenAI-compatible API for running models.", websiteUrl: "https://localai.io", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=localai.io&sz=64", cats: ["local-ai", "open-source"], isOpenSource: true, score: 80 },
  { name: "GPT4All", slug: "gpt4all", tagline: "Run LLMs on consumer hardware", description: "GPT4All runs large language models locally on everyday computers.", websiteUrl: "https://gpt4all.io", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=nomic.ai&sz=64", cats: ["local-ai", "open-source"], isOpenSource: true, score: 81 },
  { name: "Text Generation WebUI", slug: "text-generation-webui", tagline: "LLM inference interface", description: "Oobabooga's Text Generation WebUI is the most popular interface for running LLMs locally.", websiteUrl: "https://github.com/oobabooga/text-generation-webui", pricing: "FREE", logo: "https://www.google.com/s2/favicons?domain=github.com&sz=64", cats: ["local-ai", "open-source"], isOpenSource: true, score: 82 },
]

async function main() {
  console.log("Seeding full database with", ALL_TOOLS.length, "tools...")

  let created = 0, skipped = 0

  for (const tool of ALL_TOOLS) {
    const existing = await prisma.aiTool.findUnique({ where: { slug: tool.slug } })
    if (existing) { skipped++; continue }

    const categoryIds: string[] = []
    for (const catSlug of tool.cats) {
      const cat = await prisma.category.findUnique({ where: { slug: catSlug } })
      if (cat) categoryIds.push(cat.id)
    }

    await prisma.aiTool.create({
      data: {
        name: tool.name,
        slug: tool.slug,
        tagline: tool.tagline,
        description: tool.description || tool.tagline,
        websiteUrl: tool.websiteUrl,
        logo: tool.logo || null,
        pricing: tool.pricing as any,
        isFeatured: tool.isFeatured || false,
        isPublished: true,
        isOpenSource: (tool as any).isOpenSource || false,
        featuredScore: tool.score || 50,
        categories: { create: categoryIds.map((id) => ({ categoryId: id })) },
      },
    })
    created++
  }

  console.log(`Created: ${created}, Skipped (already exist): ${skipped}`)

  // Update counts
  const cats = await prisma.category.findMany({ include: { _count: { select: { tools: true } } } })
  console.log("\nCategory counts:")
  for (const c of cats.sort((a, b) => b._count.tools - a._count.tools)) {
    console.log(`  ${c.name}: ${c._count.tools} tools`)
  }

  await prisma.$disconnect()
}

main().catch((e) => { console.error(e); process.exit(1) })
