import { PrismaPg } from "@prisma/adapter-pg"
import { PrismaClient } from "@prisma/client"

const url = process.env.DATABASE_URL || "postgresql://postgres:postgres@localhost:5432/aiverse"
const adapter = new PrismaPg({ connectionString: url })
const prisma = new PrismaClient({ adapter })

// Paste the full tool list here
const ALL = [
{n:"ChatGPT",c:"Chat AI",d:"OpenAI's conversational AI assistant"},
{n:"Claude",c:"Chat AI",d:"Anthropic's AI assistant"},
{n:"Gemini",c:"Chat AI",d:"Google's multimodal AI chatbot"},
{n:"Microsoft Copilot",c:"Chat AI",d:"AI assistant integrated across Microsoft apps"},
{n:"Perplexity AI",c:"Chat AI",d:"AI-powered search and answer engine"},
{n:"Character.AI",c:"Chat AI",d:"Chat with AI-powered characters"},
{n:"Pi by Inflection",c:"Chat AI",d:"Personal AI companion for conversations"},
{n:"HuggingChat",c:"Chat AI",d:"Open-source chat interface for LLMs"},
{n:"Poe",c:"Chat AI",d:"Platform to chat with multiple AI models"},
{n:"You.com",c:"Chat AI",d:"AI search and chat assistant"},
{n:"Bing AI",c:"Chat AI",d:"Microsoft's AI-enhanced search chat"},
{n:"Grok",c:"Chat AI",d:"xAI's conversational assistant with real-time data"},
{n:"Meta AI",c:"Chat AI",d:"Meta's AI assistant across platforms"},
{n:"Mistral Le Chat",c:"Chat AI",d:"Mistral's official chat interface"},
{n:"Cohere Coral",c:"Chat AI",d:"Enterprise AI chat by Cohere"},
{n:"Jasper Chat",c:"Chat AI",d:"AI chat for marketing and content teams"},
{n:"Chatsonic",c:"Chat AI",d:"AI chatbot with web search by Writesonic"},
{n:"Kuki",c:"Chat AI",d:"Social AI chatbot for entertainment"},
{n:"Replika",c:"Chat AI",d:"AI companion for emotional support"},
{n:"Chai",c:"Chat AI",d:"Chat with AI personalities and characters"},
{n:"Inflection AI",c:"Chat AI",d:"Empathetic AI for personal conversations"},
{n:"BlenderBot",c:"Chat AI",d:"Meta's conversational AI research project"},
{n:"Mitsuku",c:"Chat AI",d:"Award-winning conversational chatbot"},
{n:"Cleverbot",c:"Chat AI",d:"Pioneering AI chatbot platform"},
{n:"AI Dungeon",c:"Chat AI",d:"AI-powered interactive storytelling"},
{n:"NovelAI",c:"Chat AI",d:"AI-assisted creative writing and chat"},
{n:"Crushon.AI",c:"Chat AI",d:"Unfiltered character AI chat platform"},
{n:"Janitor AI",c:"Chat AI",d:"Customizable AI chatbot platform"},
{n:"SpicyChat",c:"Chat AI",d:"Character-based chat AI platform"},
{n:"Venus AI",c:"Chat AI",d:"AI roleplay and character chat"},
{n:"Botify AI",c:"Chat AI",d:"Create and chat with custom AI characters"},
{n:"Woebot",c:"Chat AI",d:"Mental health AI chatbot"},
{n:"Wysa",c:"Chat AI",d:"AI mental wellness companion"},
{n:"Hume AI",c:"Chat AI",d:"Emotionally intelligent AI chat"},
{n:"SideKick AI",c:"Chat AI",d:"AI assistant for productivity"},
{n:"Andi",c:"Chat AI",d:"Conversational AI search engine"},
{n:"Phind",c:"Chat AI",d:"AI search for developers"},
{n:"Komo AI",c:"Chat AI",d:"AI-powered search and exploration"},
{n:"iAsk.ai",c:"Chat AI",d:"AI answer engine for factual queries"},
{n:"Forefront AI",c:"Chat AI",d:"Access multiple AI models in one place"},
{n:"Ora.ai",c:"Chat AI",d:"Build and share AI chatbots"},
{n:"Dante AI",c:"Chat AI",d:"Custom AI chatbot builder"},
{n:"Tidio",c:"Chat AI",d:"AI live chat for businesses"},
{n:"Intercom Fin",c:"Chat AI",d:"AI customer support chatbot"},
{n:"Drift",c:"Chat AI",d:"Conversational marketing AI platform"},
{n:"Zendesk AI",c:"Chat AI",d:"AI-powered customer service chat"},
{n:"Freshchat",c:"Chat AI",d:"AI-enhanced customer messaging"},
{n:"Crisp",c:"Chat AI",d:"Customer chat with AI automation"},
{n:"LivePerson",c:"Chat AI",d:"Conversational AI for enterprises"},
{n:"Landbot",c:"Chat AI",d:"No-code AI chatbot builder"},
{n:"ManyChat",c:"Chat AI",d:"Chat marketing automation platform"},
{n:"ChatFuel",c:"Chat AI",d:"AI chatbot for Instagram and Facebook"},
{n:"BotPress",c:"Chat AI",d:"Open-source conversational AI platform"},
{n:"Rasa",c:"Chat AI",d:"Open-source AI chatbot framework"},
{n:"Dialogflow",c:"Chat AI",d:"Google's conversational AI platform"},
{n:"Amazon Lex",c:"Chat AI",d:"AWS conversational AI service"},
{n:"IBM Watson Assistant",c:"Chat AI",d:"Enterprise AI chatbot by IBM"},
{n:"Wit.ai",c:"Chat AI",d:"Natural language for chatbots by Meta"},
{n:"Azure Bot Service",c:"Chat AI",d:"Microsoft's bot framework and hosting"},
{n:"Voiceflow",c:"Chat AI",d:"Design and deploy AI chatbots"},
{n:"Botmaker",c:"Chat AI",d:"Omnichannel chatbot platform"},
{n:"Sendbird",c:"Chat AI",d:"AI chat SDK for apps"},
{n:"Stream Chat",c:"Chat AI",d:"Chat API with AI features"},
{n:"Kommunicate",c:"Chat AI",d:"AI-powered customer support platform"},
{n:"Tars",c:"Chat AI",d:"Chatbot builder for lead generation"},
{n:"Collect.chat",c:"Chat AI",d:"Conversational form chatbot"},
{n:"MobileMonkey",c:"Chat AI",d:"Multichannel chatbot marketing"},
{n:"Userbot",c:"Chat AI",d:"AI chatbot for customer service"},
{n:"Activechat",c:"Chat AI",d:"Intelligent customer chat platform"},
{n:"Snatchbot",c:"Chat AI",d:"Free multi-platform chatbot builder"},
{n:"Botsify",c:"Chat AI",d:"AI chatbot for websites and apps"},
{n:"Gupshup",c:"Chat AI",d:"Conversational AI for business messaging"},
{n:"Yellow.ai",c:"Chat AI",d:"Enterprise conversational AI platform"},
{n:"Haptik",c:"Chat AI",d:"AI-powered conversational commerce"},
{n:"WotNot",c:"Chat AI",d:"No-code chatbot builder"},
{n:"Engati",c:"Chat AI",d:"Multichannel AI chatbot platform"},
{n:"ChatBot.com",c:"Chat AI",d:"Drag-and-drop chatbot builder"},
{n:"Flow XO",c:"Chat AI",d:"Automated chatbot workflow platform"},
{n:"Octane AI",c:"Chat AI",d:"AI quiz and chatbot for e-commerce"},
{n:"Aivo",c:"Chat AI",d:"Conversational AI for customer service"},
{n:"Kore.ai",c:"Chat AI",d:"Enterprise AI chatbot platform"},
{n:"Avaamo",c:"Chat AI",d:"Conversational AI for enterprises"},
{n:"Cognigy",c:"Chat AI",d:"Enterprise conversational AI"},
{n:"Nuance Mix",c:"Chat AI",d:"AI-powered voice and chat platform"},
{n:"NICE CXone",c:"Chat AI",d:"AI contact center platform"},
{n:"Genesys AI",c:"Chat AI",d:"AI for customer experience"},
{n:"Salesforce Einstein",c:"Chat AI",d:"AI-powered CRM assistant"},
{n:"HubSpot AI",c:"Chat AI",d:"AI-enhanced CRM and marketing chat"},
{n:"Zoho SalesIQ",c:"Chat AI",d:"AI chatbot for sales and support"},
{n:"Olark",c:"Chat AI",d:"Live chat with AI features"},
{n:"Podium",c:"Chat AI",d:"AI messaging for local businesses"},
{n:"Birdeye",c:"Chat AI",d:"AI messaging and reputation platform"},
{n:"Trengo",c:"Chat AI",d:"Team inbox with AI automation"},
{n:"Chaport",c:"Chat AI",d:"Live chat with AI chatbot"},
{n:"Nami AI",c:"Chat AI",d:"Conversational AI for subscriptions"},
{n:"Twilio Autopilot",c:"Chat AI",d:"Conversational AI on Twilio"},
{n:"Alan AI",c:"Chat AI",d:"Voice AI platform for apps"},
{n:"Sensely",c:"Chat AI",d:"AI health assistant chatbot"},
{n:"Buoy Health",c:"Chat AI",d:"AI symptom checker and health chat"},
{n:"Ada",c:"Chat AI",d:"AI customer service automation"},
{n:"DigitalGenius",c:"Chat AI",d:"AI automation for e-commerce support"},
{n:"GitHub Copilot",c:"Coding",d:"AI pair programmer by GitHub"},
{n:"Cursor",c:"Coding",d:"AI-first code editor"},
{n:"Tabnine",c:"Coding",d:"AI code completion for all IDEs"},
{n:"Amazon CodeWhisperer",c:"Coding",d:"AWS AI coding assistant"},
{n:"Replit AI",c:"Coding",d:"AI assistant in Replit IDE"},
{n:"Codeium",c:"Coding",d:"Free AI code completion tool"},
{n:"Sourcegraph Cody",c:"Coding",d:"AI coding assistant with codebase context"},
{n:"JetBrains AI",c:"Coding",d:"AI assistant in JetBrains IDEs"},
{n:"Devin AI",c:"Coding",d:"Autonomous AI software engineer"},
{n:"SWE-agent",c:"Coding",d:"AI agent for software engineering tasks"},
{n:"Aider",c:"Coding",d:"AI pair programming in terminal"},
{n:"Continue",c:"Coding",d:"Open-source AI coding assistant"},
{n:"Windsurf",c:"Coding",d:"AI-powered IDE by Codeium"},
{n:"Zed AI",c:"Coding",d:"AI features in Zed code editor"},
{n:"CodeGeeX",c:"Coding",d:"Multilingual AI code generation"},
{n:"StarCoder",c:"Coding",d:"Open-source LLM for code"},
{n:"WizardCoder",c:"Coding",d:"Instruction-tuned coding model"},
{n:"Phind",c:"Coding",d:"AI search and coding assistant"},
{n:"Pieces for Developers",c:"Coding",d:"AI-powered code snippet manager"},
{n:"Safurai",c:"Coding",d:"AI coding assistant for any IDE"},
{n:"AskCodi",c:"Coding",d:"AI code generation and explanation"},
{n:"CodeT5",c:"Coding",d:"Code understanding and generation model"},
{n:"AlphaCode",c:"Coding",d:"DeepMind's AI coding system"},
{n:"Mutable AI",c:"Coding",d:"AI coding and refactoring tool"},
{n:"Blackbox AI",c:"Coding",d:"AI code search and completion"},
{n:"CodiumAI",c:"Coding",d:"AI test generation for code"},
{n:"Diffblue",c:"Coding",d:"AI unit test generation for Java"},
{n:"Snyk AI",c:"Coding",d:"AI-powered code security scanning"},
{n:"Sonar AI",c:"Coding",d:"AI-assisted code quality analysis"},
{n:"DeepCode",c:"Coding",d:"AI semantic code analysis"},
{n:"Codiga",c:"Coding",d:"AI code reviews and static analysis"},
{n:"Swimm",c:"Coding",d:"AI-powered code documentation"},
{n:"Mintlify",c:"Coding",d:"AI-generated code documentation"},
{n:"Stenography",c:"Coding",d:"Automatic codebase documentation"},
{n:"Readable",c:"Coding",d:"AI code comments generator"},
{n:"Bito AI",c:"Coding",d:"AI code review and generation plugin"},
{n:"Warp",c:"Coding",d:"AI-powered terminal and shell"},
{n:"Fig AI",c:"Coding",d:"AI autocomplete for terminal"},
{n:"Atuin",c:"Coding",d:"AI-enhanced shell history"},
{n:"CodeSandbox AI",c:"Coding",d:"AI assistant in CodeSandbox"},
{n:"StackBlitz Codeflow",c:"Coding",d:"AI coding in browser IDE"},
{n:"Vercel v0",c:"Coding",d:"AI UI component generator"},
{n:"Bolt.new",c:"Coding",d:"AI full-stack web app builder"},
{n:"Lovable",c:"Coding",d:"AI-powered web app creation"},
{n:"AppSmith AI",c:"Coding",d:"AI for building internal tools"},
{n:"Retool AI",c:"Coding",d:"AI workflow generation for internal apps"},
{n:"Airplane AI",c:"Coding",d:"AI-generated internal tools"},
{n:"Val.town",c:"Coding",d:"AI-assisted serverless scripts"},
{n:"E2B",c:"Coding",d:"AI sandbox for code execution"},
{n:"Morph",c:"Coding",d:"AI code generation platform"},
{n:"GPT Engineer",c:"Coding",d:"AI builds entire codebases from prompt"},
{n:"MetaGPT",c:"Coding",d:"Multi-agent software development framework"},
{n:"AutoGPT",c:"Coding",d:"Autonomous GPT-based coding agent"},
{n:"AgentCoder",c:"Coding",d:"LLM agent for complex coding tasks"},
{n:"OpenHands",c:"Coding",d:"Open-source AI coding agent (OpenDevin)"},
{n:"SWE-bench",c:"Coding",d:"Benchmark for AI software engineering"},
{n:"Codesee",c:"Coding",d:"AI codebase visualization"},
{n:"Whisperer",c:"Coding",d:"AI code suggestions in VS Code"},
{n:"IntelliCode",c:"Coding",d:"Microsoft AI code recommendations"},
{n:"Visual Copilot",c:"Coding",d:"AI design to code by Builder.io"},
{n:"DhiWise",c:"Coding",d:"AI code generation from Figma"},
{n:"Locofy.ai",c:"Coding",d:"Figma to production code with AI"},
{n:"Anima",c:"Coding",d:"Design to code converter"},
{n:"TeleportHQ",c:"Coding",d:"AI-powered UI to code platform"},
{n:"Uizard",c:"Coding",d:"AI wireframe to code converter"},
{n:"Quest AI",c:"Coding",d:"React code from designs"},
{n:"Debuild",c:"Coding",d:"AI web app builder from description"},
{n:"Kombai",c:"Coding",d:"Figma to frontend code with AI"},
{n:"Durable",c:"Coding",d:"AI website builder"},
{n:"10Web",c:"Coding",d:"AI WordPress website builder"},
{n:"Framer AI",c:"Coding",d:"AI-assisted web design and code"},
{n:"Webflow AI",c:"Coding",d:"AI features in Webflow"},
{n:"Wix ADI",c:"Coding",d:"AI website design and generation"},
{n:"Hostinger AI",c:"Coding",d:"AI-powered website builder"},
{n:"Typedream AI",c:"Coding",d:"AI website creation platform"},
{n:"Pineapple Builder",c:"Coding",d:"AI website builder for startups"},
{n:"Dorik AI",c:"Coding",d:"AI-powered website creation"},
{n:"Mixo",c:"Coding",d:"AI startup website generator"},
{n:"Butternut AI",c:"Coding",d:"AI website builder in seconds"},
{n:"CodeWP",c:"Coding",d:"AI code generator for WordPress"},
{n:"MarsAi",c:"Coding",d:"AI mobile app code generator"},
{n:"FlutterFlow AI",c:"Coding",d:"AI-assisted Flutter app building"},
{n:"Draftbit",c:"Coding",d:"Visual app builder with AI"},
{n:"Thunkable AI",c:"Coding",d:"AI features in no-code app builder"},
{n:"Adalo AI",c:"Coding",d:"AI-enhanced no-code app builder"},
{n:"Glide AI",c:"Coding",d:"AI features in Glide apps"},
{n:"Bubble AI",c:"Coding",d:"AI assistance in Bubble no-code"},
{n:"Softr AI",c:"Coding",d:"AI-powered app builder from Airtable"},
{n:"Noloco",c:"Coding",d:"AI internal tool builder"},
{n:"Xata AI",c:"Coding",d:"AI-powered serverless database"},
{n:"Supabase AI",c:"Coding",d:"AI SQL query generation"},
{n:"PlanetScale AI",c:"Coding",d:"AI for MySQL database workflows"},
{n:"Neon AI",c:"Coding",d:"AI-assisted serverless Postgres"},
{n:"Hasura AI",c:"Coding",d:"AI for GraphQL API generation"},
{n:"Postman AI",c:"Coding",d:"AI-powered API testing and generation"},
{n:"Hoppscotch AI",c:"Coding",d:"Open-source API tool with AI"},
{n:"HTTPie AI",c:"Coding",d:"AI-assisted API client"},
{n:"Insomnia AI",c:"Coding",d:"AI features in REST/GraphQL client"},
{n:"Swagger AI",c:"Coding",d:"AI-enhanced API documentation"},
{n:"Stoplight AI",c:"Coding",d:"AI API design platform"},
{n:"Readme AI",c:"Coding",d:"AI for API docs and developer hubs"},
{n:"Swimlane",c:"Coding",d:"AI security automation platform"},
{n:"Dataiku",c:"Coding",d:"AI-powered data science platform"},
{n:"Midjourney",c:"Image",d:"AI image generation via Discord"},
{n:"DALL-E 3",c:"Image",d:"OpenAI's text-to-image model"},
{n:"Stable Diffusion",c:"Image",d:"Open-source image generation model"},
{n:"Adobe Firefly",c:"Image",d:"Adobe's generative AI for images"},
{n:"Canva AI",c:"Image",d:"AI image generation inside Canva"},
{n:"Ideogram",c:"Image",d:"AI image generation with text rendering"},
{n:"Playground AI",c:"Image",d:"Free AI image creation platform"},
{n:"Leonardo AI",c:"Image",d:"AI art and asset generation platform"},
{n:"Bing Image Creator",c:"Image",d:"Microsoft's DALL-E-powered image tool"},
{n:"Firefly Vector",c:"Image",d:"Adobe AI for vector graphic generation"},
{n:"Imagen",c:"Image",d:"Google's text-to-image diffusion model"},
{n:"Parti",c:"Image",d:"Google's pathways autoregressive image model"},
{n:"Stability AI",c:"Image",d:"Company behind Stable Diffusion models"},
{n:"DreamStudio",c:"Image",d:"Stability AI's official generation platform"},
{n:"Clipdrop",c:"Image",d:"AI image editing and generation suite"},
{n:"Remove.bg",c:"Image",d:"AI background removal tool"},
{n:"Cleanup.pictures",c:"Image",d:"AI object removal from images"},
{n:"Lensa AI",c:"Image",d:"AI photo editing and avatars"},
{n:"FaceApp",c:"Image",d:"AI face transformation app"},
{n:"Remini",c:"Image",d:"AI photo enhancer and restorer"},
{n:"Upscayl",c:"Image",d:"Free open-source AI image upscaler"},
{n:"Topaz Labs",c:"Image",d:"AI image enhancement software"},
{n:"Magnific AI",c:"Image",d:"AI image upscaling and enhancement"},
{n:"Real-ESRGAN",c:"Image",d:"Open-source AI image upscaler"},
{n:"Waifu2x",c:"Image",d:"AI upscaler for anime-style images"},
{n:"Artbreeder",c:"Image",d:"AI image blending and evolution"},
{n:"NightCafe",c:"Image",d:"AI art creation platform"},
{n:"DeepArt",c:"Image",d:"AI neural style transfer"},
{n:"Prisma",c:"Image",d:"AI art filter app"},
{n:"Deep Dream Generator",c:"Image",d:"Google DeepDream art platform"},
{n:"Runway ML",c:"Image",d:"AI creative tools for video and image"},
{n:"Pika Labs",c:"Image",d:"AI video and image generation"},
{n:"Kaiber",c:"Image",d:"AI visual storytelling and animation"},
{n:"Lexica",c:"Image",d:"Stable Diffusion image search and generation"},
{n:"Civitai",c:"Image",d:"Community for Stable Diffusion models"},
{n:"Tensor.Art",c:"Image",d:"AI image generation platform"},
{n:"SeaArt",c:"Image",d:"AI art generation community"},
{n:"BlueWillow",c:"Image",d:"Free AI image generation platform"},
{n:"Hotpot AI",c:"Image",d:"AI image creation and editing tools"},
{n:"Fotor AI",c:"Image",d:"AI-powered photo editor"},
{n:"Pixlr AI",c:"Image",d:"AI features in online photo editor"},
{n:"BeFunky AI",c:"Image",d:"AI photo editing and design"},
{n:"PhotoRoom",c:"Image",d:"AI product photo creator"},
{n:"Erase.bg",c:"Image",d:"AI background eraser"},
{n:"Slazzer",c:"Image",d:"Automated background removal"},
{n:"Photoroom Studio",c:"Image",d:"AI photo studio for e-commerce"},
{n:"Booth AI",c:"Image",d:"AI product photography"},
{n:"Pebblely",c:"Image",d:"AI product background generator"},
{n:"Flair AI",c:"Image",d:"AI branded content image generation"},
{n:"Mokker AI",c:"Image",d:"AI product mockup generator"},
{n:"Pack Shots AI",c:"Image",d:"AI product photo generator"},
{n:"Caspa AI",c:"Image",d:"AI lifestyle product photos"},
{n:"CreatorKit",c:"Image",d:"AI product photography for e-commerce"},
{n:"Synthesys",c:"Image",d:"AI image and video synthesis"},
{n:"DeepFaceLab",c:"Image",d:"AI face swap and deepfake tool"},
{n:"Reface",c:"Image",d:"AI face swap app"},
{n:"Avatarify",c:"Image",d:"AI avatar animation tool"},
{n:"D-ID",c:"Image",d:"AI talking head generator"},
{n:"HeyGen",c:"Image",d:"AI avatar video and image creator"},
{n:"Synthesia",c:"Image",d:"AI video avatar platform"},
{n:"Colormind",c:"Image",d:"AI color palette generator"},
{n:"Palette.fm",c:"Image",d:"AI photo colorizer"},
{n:"DeOldify",c:"Image",d:"AI image and video colorization"},
{n:"Colourise.sg",c:"Image",d:"AI photo colorization tool"},
{n:"Let's Enhance",c:"Image",d:"AI image upscaling and enhancement"},
{n:"Icons8",c:"Image",d:"AI-generated icons and illustrations"},
{n:"Khroma",c:"Image",d:"AI color tool trained on your preferences"},
{n:"Designs.ai",c:"Image",d:"AI graphic design platform"},
{n:"Looka",c:"Image",d:"AI logo and brand identity maker"},
{n:"Brandmark",c:"Image",d:"AI logo design tool"},
{n:"Tailor Brands",c:"Image",d:"AI brand and logo creator"},
{n:"Hatchful",c:"Image",d:"Shopify's AI logo maker"},
{n:"LogoAI",c:"Image",d:"AI-powered logo generator"},
{n:"Namecheap Logo Maker",c:"Image",d:"AI logo creation tool"},
{n:"Wix Logo Maker",c:"Image",d:"AI logo design in Wix"},
{n:"VistaCreate AI",c:"Image",d:"AI graphic design platform"},
{n:"Crello AI",c:"Image",d:"AI design tool for social media"},
{n:"PosterMyWall",c:"Image",d:"AI poster and graphic creator"},
{n:"Snappa",c:"Image",d:"AI-enhanced graphic design tool"},
{n:"RelayThat",c:"Image",d:"Automated multi-channel design resizing"},
{n:"Visme AI",c:"Image",d:"AI infographic and presentation maker"},
{n:"Piktochart AI",c:"Image",d:"AI infographic and report creator"},
{n:"Infogram AI",c:"Image",d:"AI data visualization and infographics"},
{n:"Venngage AI",c:"Image",d:"AI infographic design platform"},
{n:"Animate Anyone",c:"Image",d:"AI human animation from image"},
{n:"Magic Eraser",c:"Image",d:"AI unwanted object remover"},
{n:"Pixelcut",c:"Image",d:"AI photo editor for e-commerce"},
{n:"Bg.Eraser",c:"Image",d:"AI background eraser tool"},
{n:"Pincel",c:"Image",d:"AI photo editing and generation"},
{n:"ImageFX",c:"Image",d:"Google's AI image generation tool"},
{n:"Gemini Imagen",c:"Image",d:"Google DeepMind image generation"},
{n:"Flux",c:"Image",d:"Black Forest Labs image generation model"},
{n:"Grok Aurora",c:"Image",d:"xAI image generation model"},
{n:"Copilot Designer",c:"Image",d:"Microsoft AI image designer"},
{n:"Bing Create",c:"Image",d:"AI image creation in Bing"},
{n:"Meta Imagine",c:"Image",d:"Meta's AI image generator"},
{n:"Adobe Express AI",c:"Image",d:"AI tools in Adobe Express"},
{n:"Stablecog",c:"Image",d:"Open-source AI image generator"},
{n:"Mage.space",c:"Image",d:"Free Stable Diffusion platform"},
{n:"Dezgo",c:"Image",d:"Stable Diffusion image generation"},
{n:"Dreamlike.art",c:"Image",d:"AI art generation platform"},
{n:"Runway Gen-2",c:"Video",d:"AI video generation by Runway"},
{n:"Sora",c:"Video",d:"OpenAI's text-to-video model"},
{n:"Kling AI",c:"Video",d:"Kuaishou's AI video generator"},
{n:"Pika",c:"Video",d:"AI video generation and editing"},
{n:"Luma Dream Machine",c:"Video",d:"Luma AI's video generation model"},
{n:"Vidu",c:"Video",d:"AI video generation platform"},
{n:"Wan",c:"Video",d:"Alibaba's open-source video model"},
{n:"Hailuo AI",c:"Video",d:"MiniMax AI video generator"},
{n:"Haiper",c:"Video",d:"AI video generation platform"},
{n:"Genmo",c:"Video",d:"AI video and motion generation"},
{n:"Kaiber",c:"Video",d:"AI video transformation and animation"},
{n:"Stable Video Diffusion",c:"Video",d:"Stability AI's video generation model"},
{n:"AnimateDiff",c:"Video",d:"Open-source video animation model"},
{n:"ModelScope",c:"Video",d:"AI text-to-video generation"},
{n:"CogVideo",c:"Video",d:"THUDM's AI video generation model"},
{n:"Synthesia",c:"Video",d:"AI avatar video creation platform"},
{n:"HeyGen",c:"Video",d:"AI talking avatar video maker"},
{n:"D-ID",c:"Video",d:"AI video from photo and text"},
{n:"Colossyan",c:"Video",d:"AI avatar video for business"},
{n:"Hour One",c:"Video",d:"AI video production with avatars"},
{n:"Elai.io",c:"Video",d:"AI video from text with avatars"},
{n:"Lumen5",c:"Video",d:"AI video creation from blog posts"},
{n:"Pictory",c:"Video",d:"AI video creation from long content"},
{n:"InVideo AI",c:"Video",d:"AI video generation and editing"},
{n:"Fliki",c:"Video",d:"AI text-to-video with voiceover"},
{n:"Vidyo.ai",c:"Video",d:"AI video repurposing and clipping"},
{n:"Munch",c:"Video",d:"AI social media video clip creator"},
{n:"Opus Clip",c:"Video",d:"AI-powered video clipping tool"},
{n:"Vizard",c:"Video",d:"AI video repurposing platform"},
{n:"Veed.io AI",c:"Video",d:"AI video editing in browser"},
{n:"Kapwing AI",c:"Video",d:"AI video editing and subtitles"},
{n:"Descript",c:"Video",d:"AI video and podcast editing"},
{n:"Captions",c:"Video",d:"AI captioning and video creation app"},
{n:"Otter.ai",c:"Video",d:"AI transcription and meeting notes"},
{n:"Fireflies.ai",c:"Video",d:"AI meeting transcription and summary"},
{n:"Grain",c:"Video",d:"AI video coaching and meeting clips"},
{n:"Riverside AI",c:"Video",d:"AI video recording and editing"},
{n:"Squadcast AI",c:"Video",d:"AI remote recording platform"},
{n:"Cleanvoice",c:"Video",d:"AI audio and video cleanup"},
{n:"Krisp AI",c:"Video",d:"AI noise cancellation for calls"},
{n:"NVIDIA Broadcast",c:"Video",d:"AI video and audio enhancement"},
{n:"Topaz Video AI",c:"Video",d:"AI video upscaling and enhancement"},
{n:"Video Enhance AI",c:"Video",d:"AI-powered video quality improvement"},
{n:"Waifu2x Video",c:"Video",d:"AI video upscaler for anime"},
{n:"DeepFaceLab",c:"Video",d:"AI face swap in videos"},
{n:"Reface Video",c:"Video",d:"AI video face swap app"},
{n:"Wondershare Filmora AI",c:"Video",d:"AI features in Filmora editor"},
{n:"CapCut AI",c:"Video",d:"AI video editor by ByteDance"},
{n:"Adobe Premiere AI",c:"Video",d:"AI features in Premiere Pro"},
{n:"DaVinci Resolve AI",c:"Video",d:"AI-powered video color grading"},
{n:"Final Cut Pro AI",c:"Video",d:"Apple AI features in Final Cut"},
{n:"iMovie AI",c:"Video",d:"AI-assisted features in iMovie"},
{n:"Clipchamp AI",c:"Video",d:"Microsoft AI video editor"},
{n:"Animaker AI",c:"Video",d:"AI animated video creator"},
{n:"Powtoon AI",c:"Video",d:"AI presentation and video maker"},
{n:"Biteable AI",c:"Video",d:"AI video creation platform"},
{n:"Crello Video AI",c:"Video",d:"AI animated social video creator"},
{n:"Moovly",c:"Video",d:"AI-powered video production tool"},
{n:"RenderForest AI",c:"Video",d:"AI video and animation maker"},
{n:"Promo.com AI",c:"Video",d:"AI marketing video creator"},
{n:"Typito AI",c:"Video",d:"AI video and subtitle creation"},
{n:"Magisto",c:"Video",d:"AI video maker by Vimeo"},
{n:"Reel Studio",c:"Video",d:"AI short video creator"},
{n:"Nova AI",c:"Video",d:"AI video editing and subtitles"},
{n:"Submagic",c:"Video",d:"AI caption generation for shorts"},
{n:"AutoCaptions",c:"Video",d:"Automatic caption generation tool"},
{n:"Maestra",c:"Video",d:"AI transcription and subtitle generator"},
{n:"Checksub",c:"Video",d:"AI subtitle translation tool"},
{n:"Vmaker AI",c:"Video",d:"AI screen and video recorder"},
{n:"Guidde",c:"Video",d:"AI how-to video creation platform"},
{n:"Scribe AI",c:"Video",d:"AI process documentation with video"},
{n:"tl;dv",c:"Video",d:"AI meeting recorder and summarizer"},
{n:"Fathom",c:"Video",d:"AI meeting summary and notes"},
{n:"MeetGeek",c:"Video",d:"AI meeting intelligence platform"},
{n:"Airgram",c:"Video",d:"AI meeting notes and transcription"},
{n:"Notta",c:"Video",d:"AI meeting transcription and summary"},
{n:"Tactiq",c:"Video",d:"AI meeting notes for Google Meet"},
{n:"Rewind AI",c:"Video",d:"AI-powered screen and meeting recorder"},
{n:"Screenpipe",c:"Video",d:"Open-source screen recording with AI"},
{n:"Camtasia AI",c:"Video",d:"AI screen recording and video editor"},
{n:"Snagit AI",c:"Video",d:"AI screen capture and annotation"},
{n:"Loom AI",c:"Video",d:"AI summary and editing for Loom videos"},
{n:"Vidnoz",c:"Video",d:"Free AI video generator platform"},
{n:"Make-A-Video",c:"Video",d:"Meta AI text-to-video research"},
{n:"Imagen Video",c:"Video",d:"Google's video generation model"},
{n:"Phenaki",c:"Video",d:"Google long video generation model"},
{n:"VideoPoet",c:"Video",d:"Google's LLM for video generation"},
{n:"Stable Zero123",c:"Video",d:"3D asset generation from images"},
{n:"Zero123Plus",c:"Video",d:"Multi-view image generation for 3D"},
{n:"Kaedim",c:"Video",d:"AI 2D to 3D model conversion"},
{n:"Meshy AI",c:"Video",d:"AI 3D model generation platform"},
{n:"Spline AI",c:"Video",d:"AI 3D design with text prompts"},
{n:"CSM AI",c:"Video",d:"AI 3D world generation"},
{n:"Tripo3D",c:"Video",d:"AI 3D model generation"},
{n:"ElevenLabs",c:"Voice",d:"AI voice cloning and text-to-speech"},
{n:"Murf AI",c:"Voice",d:"AI voice generator for videos"},
{n:"PlayHT",c:"Voice",d:"AI text-to-speech voice generator"},
{n:"Resemble AI",c:"Voice",d:"AI voice cloning platform"},
{n:"Speechify",c:"Voice",d:"AI text-to-speech reader"},
{n:"Natural Reader",c:"Voice",d:"AI text-to-speech tool"},
{n:"Amazon Polly",c:"Voice",d:"AWS text-to-speech service"},
{n:"Google Cloud TTS",c:"Voice",d:"Google's neural text-to-speech"},
{n:"Azure TTS",c:"Voice",d:"Microsoft neural text-to-speech"},
{n:"IBM Watson TTS",c:"Voice",d:"IBM text-to-speech service"},
{n:"Deepgram",c:"Voice",d:"AI speech recognition API"},
{n:"AssemblyAI",c:"Voice",d:"AI speech transcription API"},
{n:"Rev AI",c:"Voice",d:"AI transcription and captions"},
{n:"Whisper",c:"Voice",d:"OpenAI open-source speech recognition"},
{n:"Wav2Vec",c:"Voice",d:"Meta's self-supervised speech model"},
{n:"Vosk",c:"Voice",d:"Offline open-source speech recognition"},
{n:"NVIDIA Riva",c:"Voice",d:"GPU-accelerated speech AI"},
{n:"Speechmatics",c:"Voice",d:"AI speech recognition platform"},
{n:"Verbit",c:"Voice",d:"AI transcription for media and education"},
{n:"Sonix",c:"Voice",d:"AI automated transcription service"},
{n:"Happy Scribe",c:"Voice",d:"AI transcription and subtitle tool"},
{n:"Trint",c:"Voice",d:"AI transcription and editing platform"},
{n:"Simon Says",c:"Voice",d:"AI transcription for film and media"},
{n:"Otter.ai Voice",c:"Voice",d:"AI voice transcription and meeting notes"},
{n:"Notta Voice",c:"Voice",d:"AI voice recorder and transcriber"},
{n:"Fireflies Voice",c:"Voice",d:"AI voice meeting notes"},
{n:"Descript Voice",c:"Voice",d:"AI-powered voice editing"},
{n:"Adobe Podcast AI",c:"Voice",d:"AI speech enhancement for podcasts"},
{n:"Auphonic",c:"Voice",d:"AI audio post-production tool"},
{n:"Cleanvoice AI",c:"Voice",d:"AI removes filler words from audio"},
{n:"Podcastle AI",c:"Voice",d:"AI podcast creation platform"},
{n:"Riverside AI Voice",c:"Voice",d:"AI voice quality enhancement"},
{n:"Alitu",c:"Voice",d:"AI podcast maker"},
{n:"Buzzsprout AI",c:"Voice",d:"AI podcast hosting and transcription"},
{n:"Descript Overdub",c:"Voice",d:"AI voice cloning for podcast editing"},
{n:"Replica Studios",c:"Voice",d:"AI voice actors for games and film"},
{n:"Altered AI",c:"Voice",d:"AI voice changer and cloning"},
{n:"Voicemod AI",c:"Voice",d:"Real-time AI voice changer"},
{n:"Clownfish Voice Changer",c:"Voice",d:"Real-time voice modulation"},
{n:"Krisp AI Voice",c:"Voice",d:"AI noise removal and voice enhancement"},
{n:"SpeechBrain",c:"Voice",d:"Open-source AI speech toolkit"},
{n:"LOVO AI",c:"Voice",d:"AI voiceover and text-to-speech"},
{n:"Speechelo",c:"Voice",d:"AI text-to-speech for videos"},
{n:"Respeecher",c:"Voice",d:"AI voice transformation and cloning"},
{n:"Veritone Voice",c:"Voice",d:"Enterprise AI voice cloning"},
{n:"Suno AI",c:"Voice",d:"AI music and song generation with voice"},
{n:"Udio",c:"Voice",d:"AI music generation with vocals"},
{n:"Musicfy",c:"Voice",d:"AI voice-to-song conversion"},
{n:"Kits AI",c:"Voice",d:"AI voice cloning for music"},
{n:"So.AI",c:"Voice",d:"AI voice conversion platform"},
{n:"Bark",c:"Voice",d:"Open-source multilingual TTS model"},
{n:"Coqui TTS",c:"Voice",d:"Open-source neural TTS system"},
{n:"StyleTTS",c:"Voice",d:"Style-based AI speech synthesis"},
{n:"VALL-E",c:"Voice",d:"Microsoft neural codec language model"},
{n:"VoiceBox",c:"Voice",d:"Meta's versatile speech generation model"},
{n:"AudioPaLM",c:"Voice",d:"Google's audio-language model"},
{n:"YourTTS",c:"Voice",d:"Multilingual voice cloning model"},
{n:"MockingBird",c:"Voice",d:"Real-time voice cloning in Chinese/English"},
{n:"OpenVoice",c:"Voice",d:"Instant voice cloning by MyShell AI"},
{n:"Tortoise TTS",c:"Voice",d:"High-quality AI text-to-speech"},
{n:"XTTS",c:"Voice",d:"Coqui's cross-lingual voice cloning"},
{n:"MeloTTS",c:"Voice",d:"High-quality multilingual TTS"},
{n:"CosyVoice",c:"Voice",d:"Alibaba's voice generation model"},
{n:"F5 TTS",c:"Voice",d:"Non-autoregressive TTS model"},
{n:"SoundStorm",c:"Voice",d:"Google's efficient audio generation"},
{n:"AudioGen",c:"Voice",d:"Meta's audio generation model"},
{n:"AudioCraft",c:"Voice",d:"Meta AI music and audio generation"},
{n:"Stable Audio",c:"Voice",d:"Stability AI music generation"},
{n:"MusicGen",c:"Voice",d:"Meta's music generation model"},
{n:"Riffusion",c:"Voice",d:"AI music via spectrogram diffusion"},
{n:"Boomy",c:"Voice",d:"AI music creation and distribution"},
{n:"Loudly",c:"Voice",d:"AI music platform for creators"},
{n:"Beatoven.ai",c:"Voice",d:"AI background music generator"},
{n:"Soundraw",c:"Voice",d:"AI music generation for video"},
{n:"Mubert",c:"Voice",d:"AI streaming music platform"},
{n:"Aiva",c:"Voice",d:"AI music composer"},
{n:"Amper Music",c:"Voice",d:"AI music composition tool"},
{n:"Jukedeck",c:"Voice",d:"AI music creation (acquired by TikTok)"},
{n:"Brain.fm",c:"Voice",d:"AI functional music for focus"},
{n:"Endel",c:"Voice",d:"AI-generated soundscapes for wellbeing"},
{n:"Voice.ai",c:"Voice",d:"Free real-time AI voice changer"},
{n:"FineVoice",c:"Voice",d:"AI voice toolset for creators"},
{n:"Typecast",c:"Voice",d:"AI voiceover and character creation"},
{n:"Narakeet",c:"Voice",d:"AI voiceover for videos and presentations"},
{n:"Listnr",c:"Voice",d:"AI text-to-podcast platform"},
{n:"Podium AI Voice",c:"Voice",d:"AI podcast highlight creator"},
{n:"Wondercraft",c:"Voice",d:"AI podcast production studio"},
{n:"Audiopen",c:"Voice",d:"AI voice note summarizer"},
{n:"Dictanote AI",c:"Voice",d:"AI speech-to-text notes"},
{n:"Speeko",c:"Voice",d:"AI public speaking coach"},
{n:"Orai",c:"Voice",d:"AI speech coaching app"},
{n:"VirtualSpeech",c:"Voice",d:"AI speech practice platform"},
{n:"Yoodli",c:"Voice",d:"AI communication coach"},
{n:"Speakometer",c:"Voice",d:"AI speech analysis and feedback"},
{n:"HubSpot AI",c:"Marketing",d:"AI-powered marketing automation"},
{n:"Jasper AI",c:"Marketing",d:"AI content creation for marketing"},
{n:"Copy.ai",c:"Marketing",d:"AI copywriting and marketing tool"},
{n:"Writesonic",c:"Marketing",d:"AI marketing copy generator"},
{n:"Anyword",c:"Marketing",d:"AI marketing copy with performance data"},
{n:"Persado",c:"Marketing",d:"AI language optimization for marketing"},
{n:"Phrasee",c:"Marketing",d:"AI marketing language platform"},
{n:"Seventh Sense",c:"Marketing",d:"AI email send time optimization"},
{n:"Mailchimp AI",c:"Marketing",d:"AI features in Mailchimp"},
{n:"ActiveCampaign AI",c:"Marketing",d:"AI email marketing automation"},
{n:"Klaviyo AI",c:"Marketing",d:"AI-powered e-commerce marketing"},
{n:"Salesforce Marketing AI",c:"Marketing",d:"AI marketing cloud tools"},
{n:"Marketo AI",c:"Marketing",d:"AI features in Marketo platform"},
{n:"Pardot AI",c:"Marketing",d:"Salesforce B2B AI marketing"},
{n:"Brevo AI",c:"Marketing",d:"AI email and SMS marketing"},
{n:"Omnisend AI",c:"Marketing",d:"AI e-commerce marketing automation"},
{n:"Drip AI",c:"Marketing",d:"AI marketing automation for DTC brands"},
{n:"ConvertKit AI",c:"Marketing",d:"AI features for email creators"},
{n:"Beehiiv AI",c:"Marketing",d:"AI newsletter creation and growth"},
{n:"Substack AI",c:"Marketing",d:"AI writing features for newsletters"},
{n:"Surfer SEO",c:"Marketing",d:"AI-powered SEO content optimization"},
{n:"Semrush AI",c:"Marketing",d:"AI SEO and marketing analytics"},
{n:"Ahrefs AI",c:"Marketing",d:"AI features in SEO toolkit"},
{n:"Clearscope",c:"Marketing",d:"AI content optimization for SEO"},
{n:"MarketMuse",c:"Marketing",d:"AI content intelligence for SEO"},
{n:"Frase.io",c:"Marketing",d:"AI SEO content research and writing"},
{n:"NeuronWriter",c:"Marketing",d:"AI SEO content writer"},
{n:"Alli AI",c:"Marketing",d:"AI SEO automation platform"},
{n:"LinkWhisper",c:"Marketing",d:"AI internal linking for WordPress"},
{n:"RankMath AI",c:"Marketing",d:"AI SEO plugin for WordPress"},
{n:"Yoast AI",c:"Marketing",d:"AI SEO features in Yoast"},
{n:"Moz AI",c:"Marketing",d:"AI insights in Moz SEO tools"},
{n:"SpyFu AI",c:"Marketing",d:"AI competitor keyword research"},
{n:"SE Ranking AI",c:"Marketing",d:"AI-enhanced rank tracking"},
{n:"Mangools AI",c:"Marketing",d:"AI keyword research tools"},
{n:"AdCreative.ai",c:"Marketing",d:"AI ad creative generation"},
{n:"Pencil AI",c:"Marketing",d:"AI ad generation and testing"},
{n:"Smartly.io AI",c:"Marketing",d:"AI social media ad automation"},
{n:"Pattern89",c:"Marketing",d:"AI ad creative performance prediction"},
{n:"Phrasee Ads",c:"Marketing",d:"AI-optimized ad copy"},
{n:"Albert AI",c:"Marketing",d:"AI autonomous digital marketing"},
{n:"Acquisio AI",c:"Marketing",d:"AI PPC campaign management"},
{n:"Opteo",c:"Marketing",d:"AI Google Ads optimization"},
{n:"Revealbot",c:"Marketing",d:"AI ad automation for Meta and Google"},
{n:"Madgicx",c:"Marketing",d:"AI Facebook ads intelligence"},
{n:"Zalster",c:"Marketing",d:"AI social media advertising"},
{n:"Trapica",c:"Marketing",d:"AI ad targeting optimization"},
{n:"Cortex AI",c:"Marketing",d:"AI social content performance insights"},
{n:"Sprout Social AI",c:"Marketing",d:"AI social media management"},
{n:"Hootsuite Insights AI",c:"Marketing",d:"AI social listening and scheduling"},
{n:"Buffer AI",c:"Marketing",d:"AI social media content suggestions"},
{n:"Later AI",c:"Marketing",d:"AI caption generation for social"},
{n:"Planoly AI",c:"Marketing",d:"AI social planning and scheduling"},
{n:"SocialBee AI",c:"Marketing",d:"AI social media content recycling"},
{n:"Missinglettr",c:"Marketing",d:"AI social media drip campaigns"},
{n:"Sendible AI",c:"Marketing",d:"AI features in social management"},
{n:"MeetEdgar AI",c:"Marketing",d:"AI social media scheduling"},
{n:"ContentStudio AI",c:"Marketing",d:"AI social and content marketing"},
{n:"Lately AI",c:"Marketing",d:"AI repurposes content for social"},
{n:"Ocoya",c:"Marketing",d:"AI social media content creation"},
{n:"Vista Social AI",c:"Marketing",d:"AI social media management"},
{n:"Publer AI",c:"Marketing",d:"AI scheduling for all social platforms"},
{n:"Mentionlytics",c:"Marketing",d:"AI social media monitoring"},
{n:"Brand24 AI",c:"Marketing",d:"AI social listening and media monitoring"},
{n:"Talkwalker AI",c:"Marketing",d:"AI consumer intelligence platform"},
{n:"Brandwatch AI",c:"Marketing",d:"AI social media analytics"},
{n:"Synthesio AI",c:"Marketing",d:"AI consumer and market intelligence"},
{n:"Meltwater AI",c:"Marketing",d:"AI media intelligence platform"},
{n:"Critical Mention",c:"Marketing",d:"AI broadcast and media monitoring"},
{n:"Cision AI",c:"Marketing",d:"AI PR and media monitoring"},
{n:"PR Newswire AI",c:"Marketing",d:"AI press release distribution"},
{n:"Prezly AI",c:"Marketing",d:"AI PR newsroom platform"},
{n:"Propel PRM",c:"Marketing",d:"AI public relations management"},
{n:"Muck Rack AI",c:"Marketing",d:"AI media database and PR tools"},
{n:"Anewstip AI",c:"Marketing",d:"AI media contact research"},
{n:"Prowly AI",c:"Marketing",d:"AI PR software platform"},
{n:"Voxco AI",c:"Marketing",d:"AI market research platform"},
{n:"Qualtrics AI",c:"Marketing",d:"AI experience management platform"},
{n:"SurveyMonkey AI",c:"Marketing",d:"AI survey insights and analysis"},
{n:"Typeform AI",c:"Marketing",d:"AI-powered form and survey creation"},
{n:"Hotjar AI",c:"Marketing",d:"AI heatmaps and user behavior insights"},
{n:"Crazy Egg AI",c:"Marketing",d:"AI website optimization tools"},
{n:"Optimizely AI",c:"Marketing",d:"AI A/B testing and experimentation"},
{n:"VWO AI",c:"Marketing",d:"AI conversion rate optimization"},
{n:"Unbounce AI",c:"Marketing",d:"AI landing page builder and optimizer"},
{n:"Instapage AI",c:"Marketing",d:"AI landing page personalization"},
{n:"Leadpages AI",c:"Marketing",d:"AI landing page creation"},
{n:"ClickFunnels AI",c:"Marketing",d:"AI sales funnel builder"},
{n:"CartFlows AI",c:"Marketing",d:"AI WordPress sales funnels"},
{n:"Funnelytics",c:"Marketing",d:"AI funnel analytics and mapping"},
{n:"Amplitude AI",c:"Marketing",d:"AI product analytics platform"},
{n:"Mixpanel AI",c:"Marketing",d:"AI event analytics and insights"},
{n:"Heap AI",c:"Marketing",d:"AI digital insights platform"},
{n:"FullStory AI",c:"Marketing",d:"AI digital experience analytics"},
{n:"Mouseflow AI",c:"Marketing",d:"AI session recording and heatmaps"},
{n:"Segment AI",c:"Marketing",d:"AI customer data platform"},
{n:"mParticle AI",c:"Marketing",d:"AI customer data infrastructure"},
{n:"Braze AI",c:"Marketing",d:"AI customer engagement platform"},
{n:"Iterable AI",c:"Marketing",d:"AI cross-channel marketing platform"},
{n:"Customer.io AI",c:"Marketing",d:"AI behavioral marketing automation"},
{n:"Intercom AI Marketing",c:"Marketing",d:"AI customer messaging and marketing"},
{n:"Notion AI",c:"Productivity",d:"AI assistant inside Notion workspace"},
{n:"Microsoft Copilot 365",c:"Productivity",d:"AI in Word, Excel, Teams and more"},
{n:"Google Workspace AI",c:"Productivity",d:"AI features in Google Docs and Gmail"},
{n:"Zapier AI",c:"Productivity",d:"AI-powered workflow automation"},
{n:"Make AI",c:"Productivity",d:"AI scenario automation platform"},
{n:"Monday AI",c:"Productivity",d:"AI features in Monday.com"},
{n:"Asana AI",c:"Productivity",d:"AI-powered project management"},
{n:"ClickUp AI",c:"Productivity",d:"AI project manager and writer"},
{n:"Linear AI",c:"Productivity",d:"AI features in Linear issue tracker"},
{n:"Jira AI",c:"Productivity",d:"AI in Atlassian Jira"},
{n:"Confluence AI",c:"Productivity",d:"AI knowledge base in Confluence"},
{n:"Trello AI",c:"Productivity",d:"AI butler automation in Trello"},
{n:"Basecamp AI",c:"Productivity",d:"AI features in Basecamp"},
{n:"Airtable AI",c:"Productivity",d:"AI database and spreadsheet platform"},
{n:"Coda AI",c:"Productivity",d:"AI-powered doc and database"},
{n:"Fibery AI",c:"Productivity",d:"AI-enhanced knowledge management"},
{n:"Height AI",c:"Productivity",d:"AI project management tool"},
{n:"Hive AI",c:"Productivity",d:"AI project management platform"},
{n:"TeamWork AI",c:"Productivity",d:"AI features in Teamwork PM"},
{n:"Wrike AI",c:"Productivity",d:"AI-powered work management"},
{n:"Smartsheet AI",c:"Productivity",d:"AI in collaborative spreadsheets"},
{n:"Miro AI",c:"Productivity",d:"AI visual collaboration and whiteboard"},
{n:"FigJam AI",c:"Productivity",d:"AI brainstorming in Figma board"},
{n:"Mural AI",c:"Productivity",d:"AI-enhanced visual collaboration"},
{n:"Lucidchart AI",c:"Productivity",d:"AI diagramming and flowcharts"},
{n:"Whimsical AI",c:"Productivity",d:"AI wireframes and mind maps"},
{n:"Creately AI",c:"Productivity",d:"AI visual collaboration platform"},
{n:"Xtensio AI",c:"Productivity",d:"AI business document creator"},
{n:"Taskade AI",c:"Productivity",d:"AI task and project management"},
{n:"Things 3 AI",c:"Productivity",d:"AI task management for Apple"},
{n:"Todoist AI",c:"Productivity",d:"AI smart scheduling in Todoist"},
{n:"OmniFocus AI",c:"Productivity",d:"AI features in OmniFocus"},
{n:"Fantastical AI",c:"Productivity",d:"AI natural language calendar events"},
{n:"Reclaim AI",c:"Productivity",d:"AI calendar scheduling assistant"},
{n:"Motion AI",c:"Productivity",d:"AI calendar and task prioritizer"},
{n:"Clockwise AI",c:"Productivity",d:"AI meeting scheduling optimizer"},
{n:"Calendly AI",c:"Productivity",d:"AI scheduling and booking tool"},
{n:"Otter AI Productivity",c:"Productivity",d:"AI meeting notes and action items"},
{n:"Fireflies Productivity",c:"Productivity",d:"AI meeting notes automation"},
{n:"Grain Productivity",c:"Productivity",d:"AI meeting highlights and clips"},
{n:"tl;dv Productivity",c:"Productivity",d:"AI meeting summary and CRM sync"},
{n:"Supernormal",c:"Productivity",d:"AI meeting notes with integrations"},
{n:"Tactiq Productivity",c:"Productivity",d:"AI real-time meeting notes"},
{n:"Rewind AI Productivity",c:"Productivity",d:"AI searchable record of everything"},
{n:"Mem AI Productivity",c:"Productivity",d:"AI-organized memory workspace"},
{n:"Limitless AI",c:"Productivity",d:"AI wearable for capturing context"},
{n:"Reflect AI",c:"Productivity",d:"AI-powered note-taking tool"},
{n:"Readwise AI",c:"Productivity",d:"AI reading highlights and review"},
{n:"Matter AI",c:"Productivity",d:"AI reading and newsletter curation"},
{n:"Omnivore AI",c:"Productivity",d:"Open-source AI read-it-later app"},
{n:"Pocket AI",c:"Productivity",d:"Mozilla AI reading list tool"},
{n:"Instapaper AI",c:"Productivity",d:"AI article saving and reading"},
{n:"Liner AI",c:"Productivity",d:"AI web highlighter and chatbot"},
{n:"Glasp AI",c:"Productivity",d:"AI knowledge highlighter and curator"},
{n:"Napkin AI",c:"Productivity",d:"AI turns notes into visuals"},
{n:"Whisk",c:"Productivity",d:"AI recipe and meal planning tool"},
{n:"Superhuman AI",c:"Productivity",d:"AI-powered email productivity tool"},
{n:"SaneBox AI",c:"Productivity",d:"AI email triage and filtering"},
{n:"Shortwave AI",c:"Productivity",d:"AI email summarization and drafts"},
{n:"Spike AI",c:"Productivity",d:"AI-enhanced email and messaging"},
{n:"Missive AI",c:"Productivity",d:"AI team email and chat collaboration"},
{n:"Front AI",c:"Productivity",d:"AI customer communication inbox"},
{n:"Hey AI",c:"Productivity",d:"AI email management by Basecamp"},
{n:"Edison Mail AI",c:"Productivity",d:"AI smart email organizer"},
{n:"Canary Mail AI",c:"Productivity",d:"AI email security and management"},
{n:"Airmail AI",c:"Productivity",d:"AI email client for Apple"},
{n:"Astro AI",c:"Productivity",d:"AI email organization assistant"},
{n:"Mailbird AI",c:"Productivity",d:"AI email client for Windows"},
{n:"Postbox AI",c:"Productivity",d:"AI-enhanced email client"},
{n:"Sanebox",c:"Productivity",d:"AI email filtering and organization"},
{n:"Clean Email AI",c:"Productivity",d:"AI bulk email cleaner"},
{n:"Unroll.me AI",c:"Productivity",d:"AI subscription email management"},
{n:"Mailstrom AI",c:"Productivity",d:"AI email management and cleanup"},
{n:"AI Transcription",c:"Productivity",d:"AI audio to text productivity"},
{n:"Krisp Productivity",c:"Productivity",d:"AI noise cancellation for meetings"},
{n:"Loom AI",c:"Productivity",d:"AI video messages for async work"},
{n:"Pitch AI",c:"Productivity",d:"AI presentation creation platform"},
{n:"Beautiful.ai",c:"Productivity",d:"AI presentation design tool"},
{n:"Tome AI",c:"Productivity",d:"AI presentation and storytelling"},
{n:"Decktopus AI",c:"Productivity",d:"AI presentation generator"},
{n:"SlidesAI",c:"Productivity",d:"AI Google Slides content creator"},
{n:"MagicSlides",c:"Productivity",d:"AI slide deck generator"},
{n:"Gamma AI",c:"Productivity",d:"AI-powered presentations and docs"},
{n:"Plus AI",c:"Productivity",d:"AI slide generation in Google Slides"},
{n:"Slidebean AI",c:"Productivity",d:"AI startup pitch deck design"},
{n:"Visme Productivity",c:"Productivity",d:"AI infographic and slide creator"},
{n:"Zoho Writer AI",c:"Productivity",d:"AI writing in Zoho Docs"},
{n:"Dropbox AI",c:"Productivity",d:"AI document summarization in Dropbox"},
{n:"Box AI",c:"Productivity",d:"AI for enterprise document management"},
{n:"Adobe Acrobat AI",c:"Productivity",d:"AI PDF summarization and assistant"},
{n:"DocuSign AI",c:"Productivity",d:"AI contract analysis and drafting"},
{n:"PandaDoc AI",c:"Productivity",d:"AI document creation and signing"},
{n:"Smallpdf AI",c:"Productivity",d:"AI PDF tools and compression"},
{n:"Salesforce Einstein",c:"Business",d:"AI for CRM and sales forecasting"},
{n:"HubSpot AI CRM",c:"Business",d:"AI-powered CRM and sales tools"},
{n:"Pipedrive AI",c:"Business",d:"AI sales pipeline management"},
{n:"Zoho CRM AI",c:"Business",d:"AI sales assistant Zia in Zoho"},
{n:"Monday Sales AI",c:"Business",d:"AI sales CRM on Monday.com"},
{n:"Copper AI",c:"Business",d:"AI CRM for Google Workspace"},
{n:"Freshsales AI",c:"Business",d:"AI sales CRM by Freshworks"},
{n:"Close AI",c:"Business",d:"AI inside sales CRM"},
{n:"Gong AI",c:"Business",d:"AI revenue intelligence platform"},
{n:"Chorus.ai",c:"Business",d:"AI conversation intelligence for sales"},
{n:"Outreach AI",c:"Business",d:"AI sales execution platform"},
{n:"Salesloft AI",c:"Business",d:"AI sales engagement platform"},
{n:"Apollo AI",c:"Business",d:"AI sales intelligence and outreach"},
{n:"Lavender AI",c:"Business",d:"AI email coach for sales reps"},
{n:"Regie.ai",c:"Business",d:"AI sales content and sequences"},
{n:"Smartwriter AI",c:"Business",d:"AI personalized cold email writer"},
{n:"Klenty AI",c:"Business",d:"AI sales cadence platform"},
{n:"Lemlist AI",c:"Business",d:"AI cold email and outreach platform"},
{n:"Reply.io AI",c:"Business",d:"AI sales email automation"},
{n:"Woodpecker AI",c:"Business",d:"AI cold email platform"},
{n:"Instantly AI",c:"Business",d:"AI cold email scaling platform"},
{n:"Hunter AI",c:"Business",d:"AI email finder and outreach"},
{n:"Snov.io AI",c:"Business",d:"AI sales automation and email"},
{n:"ZoomInfo AI",c:"Business",d:"AI B2B data and sales intelligence"},
{n:"Bombora AI",c:"Business",d:"AI intent data for B2B sales"},
{n:"Clearbit AI",c:"Business",d:"AI data enrichment for sales"},
{n:"Lusha AI",c:"Business",d:"AI B2B contact data platform"},
{n:"Cognism AI",c:"Business",d:"AI sales intelligence and prospecting"},
{n:"Clay AI",c:"Business",d:"AI data enrichment for outbound"},
{n:"Humanlinker",c:"Business",d:"AI personalization for B2B sales"},
{n:"People.ai",c:"Business",d:"AI revenue operations platform"},
{n:"Clari AI",c:"Business",d:"AI revenue forecasting platform"},
{n:"Boostup AI",c:"Business",d:"AI revenue intelligence"},
{n:"Aviso AI",c:"Business",d:"AI revenue operations and forecasting"},
{n:"Crayon AI",c:"Business",d:"AI competitive intelligence platform"},
{n:"Klue AI",c:"Business",d:"AI competitive enablement platform"},
{n:"Kompyte AI",c:"Business",d:"AI competitive intelligence tracking"},
{n:"Contify AI",c:"Business",d:"AI market intelligence platform"},
{n:"Owler AI",c:"Business",d:"AI business news and intelligence"},
{n:"CB Insights AI",c:"Business",d:"AI tech market intelligence"},
{n:"Pitchbook AI",c:"Business",d:"AI venture and private equity data"},
{n:"Crunchbase AI",c:"Business",d:"AI startup and investment data"},
{n:"Dealroom AI",c:"Business",d:"AI startup intelligence platform"},
{n:"Affinity AI",c:"Business",d:"AI relationship intelligence CRM"},
{n:"Carta AI",c:"Business",d:"AI equity management platform"},
{n:"Stripe AI",c:"Business",d:"AI fraud detection and payments"},
{n:"Brex AI",c:"Business",d:"AI spend management for startups"},
{n:"Ramp AI",c:"Business",d:"AI corporate card and expense mgmt"},
{n:"Expensify AI",c:"Business",d:"AI expense report automation"},
{n:"Concur AI",c:"Business",d:"AI travel and expense management"},
{n:"Divvy AI",c:"Business",d:"AI budgeting and expense tracking"},
{n:"Procurify AI",c:"Business",d:"AI procurement and spend management"},
{n:"Coupa AI",c:"Business",d:"AI business spend management"},
{n:"SAP Ariba AI",c:"Business",d:"AI procurement and supply chain"},
{n:"QuickBooks AI",c:"Business",d:"AI bookkeeping and accounting"},
{n:"Xero AI",c:"Business",d:"AI-powered cloud accounting"},
{n:"FreshBooks AI",c:"Business",d:"AI invoicing and accounting"},
{n:"Wave AI",c:"Business",d:"AI accounting for small business"},
{n:"Sage AI",c:"Business",d:"AI accounting and ERP platform"},
{n:"NetSuite AI",c:"Business",d:"AI ERP and financial management"},
{n:"Bench AI",c:"Business",d:"AI bookkeeping service"},
{n:"Pilot AI",c:"Business",d:"AI accounting and CFO services"},
{n:"Pulley AI",c:"Business",d:"AI equity and cap table management"},
{n:"Vena AI",c:"Business",d:"AI financial planning platform"},
{n:"Cube AI",c:"Business",d:"AI FP&A and spreadsheet platform"},
{n:"Mosaic AI",c:"Business",d:"AI strategic finance platform"},
{n:"Runway Financial",c:"Business",d:"AI financial modeling platform"},
{n:"Causal AI",c:"Business",d:"AI financial modeling tool"},
{n:"LiveFlow AI",c:"Business",d:"AI financial reporting in Google Sheets"},
{n:"Datarails AI",c:"Business",d:"AI FP&A for Excel users"},
{n:"Anaplan AI",c:"Business",d:"AI connected planning platform"},
{n:"Workday AI",c:"Business",d:"AI HR and financial management"},
{n:"Rippling AI",c:"Business",d:"AI HR and IT workforce platform"},
{n:"BambooHR AI",c:"Business",d:"AI HR software for SMBs"},
{n:"Greenhouse AI",c:"Business",d:"AI recruiting software"},
{n:"Lever AI",c:"Business",d:"AI talent acquisition platform"},
{n:"Workable AI",c:"Business",d:"AI hiring and recruiting software"},
{n:"iCIMS AI",c:"Business",d:"AI talent cloud platform"},
{n:"SmartRecruiters AI",c:"Business",d:"AI enterprise recruiting platform"},
{n:"Beamery AI",c:"Business",d:"AI talent lifecycle management"},
{n:"Fetcher AI",c:"Business",d:"AI talent sourcing automation"},
{n:"Paradox AI",c:"Business",d:"AI recruiting assistant Olivia"},
{n:"HiredScore AI",c:"Business",d:"AI talent intelligence platform"},
{n:"Eightfold AI",c:"Business",d:"AI talent intelligence platform"},
{n:"SeekOut AI",c:"Business",d:"AI talent search platform"},
{n:"Findem AI",c:"Business",d:"AI people intelligence for talent"},
{n:"Vervoe AI",c:"Business",d:"AI skills assessment for hiring"},
{n:"Codility AI",c:"Business",d:"AI technical recruiting platform"},
{n:"HackerRank AI",c:"Business",d:"AI coding assessments for hiring"},
{n:"TestGorilla AI",c:"Business",d:"AI pre-employment testing"},
{n:"Pymetrics AI",c:"Business",d:"AI bias-free hiring assessments"},
{n:"Knack AI",c:"Business",d:"AI aptitude and skills assessment"},
{n:"Crystalknows AI",c:"Business",d:"AI personality-based hiring insights"},
{n:"Humata AI",c:"Business",d:"AI document analysis for business"},
{n:"Klarity AI",c:"Business",d:"AI contract review and analysis"},
{n:"Ironclad AI",c:"Business",d:"AI contract lifecycle management"},
{n:"Lexion AI",c:"Business",d:"AI contract management platform"},
{n:"SpotDraft AI",c:"Business",d:"AI contract management software"},
{n:"Summize AI",c:"Business",d:"AI contract analysis tool"},
{n:"Khan Academy Khanmigo",c:"Education",d:"AI tutor for students on Khan Academy"},
{n:"Duolingo AI",c:"Education",d:"AI language learning personalization"},
{n:"Coursera AI",c:"Education",d:"AI-guided online learning platform"},
{n:"Chegg AI",c:"Education",d:"AI homework help and tutoring"},
{n:"Quizlet AI",c:"Education",d:"AI flashcards and study tools"},
{n:"Photomath",c:"Education",d:"AI math problem solver from camera"},
{n:"Wolfram Alpha AI",c:"Education",d:"Computational knowledge AI engine"},
{n:"Socratic by Google",c:"Education",d:"AI homework help app by Google"},
{n:"Brainly AI",c:"Education",d:"AI-powered student Q&A platform"},
{n:"Mathway AI",c:"Education",d:"AI math problem solver"},
{n:"Numerade AI",c:"Education",d:"AI STEM video tutoring platform"},
{n:"Wyzant AI",c:"Education",d:"AI-assisted tutor matching"},
{n:"Preply AI",c:"Education",d:"AI language tutoring platform"},
{n:"iTalki AI",c:"Education",d:"AI language practice and tutors"},
{n:"Babbel AI",c:"Education",d:"AI speech recognition language learning"},
{n:"Rosetta Stone AI",c:"Education",d:"AI-powered language immersion"},
{n:"Pimsleur AI",c:"Education",d:"AI audio-based language learning"},
{n:"Memrise AI",c:"Education",d:"AI spaced repetition language app"},
{n:"Lingoda AI",c:"Education",d:"AI and live language learning"},
{n:"Busuu AI",c:"Education",d:"AI language learning community"},
{n:"Anki AI",c:"Education",d:"AI-enhanced spaced repetition flashcards"},
{n:"Quizbot AI",c:"Education",d:"AI quiz and flashcard generator"},
{n:"Conker AI",c:"Education",d:"AI quiz generator for educators"},
{n:"Kahoot AI",c:"Education",d:"AI quiz creation platform"},
{n:"Mentimeter AI",c:"Education",d:"AI interactive presentations for education"},
{n:"Nearpod AI",c:"Education",d:"AI interactive lessons platform"},
{n:"Pear Deck AI",c:"Education",d:"AI formative assessment in slides"},
{n:"Padlet AI",c:"Education",d:"AI collaborative board for education"},
{n:"Seesaw AI",c:"Education",d:"AI learning platform for K-12"},
{n:"ClassDojo AI",c:"Education",d:"AI classroom communication platform"},
{n:"Remind AI",c:"Education",d:"AI school communication tool"},
{n:"Bloomz AI",c:"Education",d:"AI parent-teacher communication"},
{n:"Edmodo AI",c:"Education",d:"AI social learning network"},
{n:"Schoology AI",c:"Education",d:"AI learning management system"},
{n:"Canvas AI",c:"Education",d:"AI features in Canvas LMS"},
{n:"Blackboard AI",c:"Education",d:"AI in Blackboard LMS"},
{n:"Moodle AI",c:"Education",d:"AI-enhanced open-source LMS"},
{n:"D2L Brightspace AI",c:"Education",d:"AI learning platform with analytics"},
{n:"Google Classroom AI",c:"Education",d:"AI features in Google Classroom"},
{n:"Turnitin AI Detection",c:"Education",d:"AI academic integrity tool"},
{n:"Gradescope AI",c:"Education",d:"AI grading and assessment tool"},
{n:"Formative AI",c:"Education",d:"AI real-time student assessment"},
{n:"Edulastic AI",c:"Education",d:"AI formative assessment platform"},
{n:"IXL AI",c:"Education",d:"AI adaptive practice for K-12"},
{n:"DreamBox AI",c:"Education",d:"AI adaptive math learning"},
{n:"Amplify AI",c:"Education",d:"AI literacy and science programs"},
{n:"Age of Learning AI",c:"Education",d:"ABCmouse AI early learning platform"},
{n:"Lexia AI",c:"Education",d:"AI reading instruction program"},
{n:"Reading Eggs AI",c:"Education",d:"AI-powered reading for kids"},
{n:"Zearn AI",c:"Education",d:"AI math learning for students"},
{n:"ST Math AI",c:"Education",d:"AI visual math learning platform"},
{n:"Carnegie Learning AI",c:"Education",d:"AI math tutoring platform"},
{n:"McGraw-Hill ALEKS",c:"Education",d:"AI adaptive learning for math"},
{n:"Pearson AI",c:"Education",d:"AI personalized learning platform"},
{n:"Knewton AI",c:"Education",d:"AI adaptive learning technology"},
{n:"Squirrel AI",c:"Education",d:"AI adaptive tutoring system"},
{n:"Cognii AI",c:"Education",d:"AI conversational assessment tool"},
{n:"Third Space Learning AI",c:"Education",d:"AI-supported math tutoring"},
{n:"Varsity Tutors AI",c:"Education",d:"AI-enhanced live tutoring platform"},
{n:"Paper AI",c:"Education",d:"AI homework help on-demand"},
{n:"Tutor.com AI",c:"Education",d:"AI and live tutoring platform"},
{n:"Smarthinking AI",c:"Education",d:"AI online tutoring service"},
{n:"Elevate AI",c:"Education",d:"AI brain training app"},
{n:"Lumosity AI",c:"Education",d:"AI cognitive training platform"},
{n:"Peak AI",c:"Education",d:"AI brain training app"},
{n:"Duolingo Math AI",c:"Education",d:"AI-powered math practice app"},
{n:"Brilliant AI",c:"Education",d:"AI-assisted STEM learning platform"},
{n:"Codecademy AI",c:"Education",d:"AI-powered coding education platform"},
{n:"freeCodeCamp AI",c:"Education",d:"AI coding practice and projects"},
{n:"Udemy AI",c:"Education",d:"AI course recommendations on Udemy"},
{n:"edX AI",c:"Education",d:"AI-enhanced online courses"},
{n:"LinkedIn Learning AI",c:"Education",d:"AI skill recommendations for learning"},
{n:"Skillshare AI",c:"Education",d:"AI project-based creative learning"},
{n:"Pluralsight AI",c:"Education",d:"AI tech skills development platform"},
{n:"A Cloud Guru AI",c:"Education",d:"AI cloud certification learning"},
{n:"DataCamp AI",c:"Education",d:"AI data science learning platform"},
{n:"365 Data Science AI",c:"Education",d:"AI data analytics education"},
{n:"DeepLearning.AI",c:"Education",d:"AI deep learning and ML courses"},
{n:"Fast.ai AI",c:"Education",d:"Practical deep learning education"},
{n:"Hugging Face Courses",c:"Education",d:"Free AI and ML education"},
{n:"Google AI Courses",c:"Education",d:"Free AI/ML learning from Google"},
{n:"Microsoft Learn AI",c:"Education",d:"Free AI learning paths from Microsoft"},
{n:"AWS Training AI",c:"Education",d:"AI cloud certification training"},
{n:"Socratica AI",c:"Education",d:"AI math and science YouTube education"},
{n:"CK-12 AI",c:"Education",d:"AI personalized K-12 learning platform"},
{n:"OpenStax AI",c:"Education",d:"AI-enhanced open textbook platform"},
{n:"Activelearner AI",c:"Education",d:"AI active recall learning tool"},
{n:"StudySmarter AI",c:"Education",d:"AI study platform and flashcards"},
{n:"Kognity AI",c:"Education",d:"AI-powered digital textbooks"},
{n:"Acer EduConnect AI",c:"Education",d:"AI education device management"},
{n:"Classcraft AI",c:"Education",d:"AI gamified learning platform"},
{n:"Gimkit AI",c:"Education",d:"AI learning game platform"},
{n:"Blooket AI",c:"Education",d:"AI game-based learning tool"},
{n:"Quizizz AI",c:"Education",d:"AI quiz and game-based learning"},
{n:"Wooclap AI",c:"Education",d:"AI audience interaction for classes"},
{n:"Poll Everywhere AI",c:"Education",d:"AI live polling for education"},
{n:"Slido AI",c:"Education",d:"AI audience Q&A and polling"},
{n:"Zapier",c:"Automation",d:"No-code automation across 5000+ apps"},
{n:"Make (Integromat)",c:"Automation",d:"Visual workflow automation platform"},
{n:"n8n",c:"Automation",d:"Open-source workflow automation"},
{n:"Activepieces",c:"Automation",d:"Open-source no-code automation"},
{n:"Pipedream",c:"Automation",d:"Developer automation with AI steps"},
{n:"Workato",c:"Automation",d:"Enterprise AI integration platform"},
{n:"Tray.io",c:"Automation",d:"AI-powered enterprise automation"},
{n:"Boomi AI",c:"Automation",d:"AI integration and automation platform"},
{n:"MuleSoft AI",c:"Automation",d:"AI API and integration platform"},
{n:"Azure Logic Apps AI",c:"Automation",d:"AI cloud workflow automation by Microsoft"},
{n:"AWS Step Functions",c:"Automation",d:"AI serverless workflow orchestration"},
{n:"Google Cloud Workflows AI",c:"Automation",d:"AI workflow automation on GCP"},
{n:"UiPath AI",c:"Automation",d:"AI-powered RPA and automation platform"},
{n:"Automation Anywhere",c:"Automation",d:"AI-powered intelligent automation"},
{n:"Blue Prism AI",c:"Automation",d:"Enterprise AI and RPA platform"},
{n:"Power Automate AI",c:"Automation",d:"Microsoft AI workflow automation"},
{n:"SS&C Blue Prism",c:"Automation",d:"AI digital workers and RPA"},
{n:"NICE AI Automation",c:"Automation",d:"AI robotic process automation"},
{n:"Kryon AI",c:"Automation",d:"AI full-cycle automation platform"},
{n:"Servicetrace AI",c:"Automation",d:"AI automation technology platform"},
{n:"Redwood AI",c:"Automation",d:"AI business process automation"},
{n:"Softomotive AI",c:"Automation",d:"AI RPA platform (now Microsoft)"},
{n:"Kofax AI",c:"Automation",d:"AI intelligent automation platform"},
{n:"ABBYY AI",c:"Automation",d:"AI document processing and IDP"},
{n:"Hyperscience AI",c:"Automation",d:"AI document and data processing"},
{n:"Instabase AI",c:"Automation",d:"AI unstructured data automation"},
{n:"Nanonets AI",c:"Automation",d:"AI data extraction and OCR"},
{n:"Rossum AI",c:"Automation",d:"AI document data extraction"},
{n:"Docparser AI",c:"Automation",d:"AI PDF and document parsing"},
{n:"Parseur AI",c:"Automation",d:"AI email and document parsing"},
{n:"Mailparser AI",c:"Automation",d:"AI email data extraction"},
{n:"Xtracta AI",c:"Automation",d:"AI document data capture"},
{n:"Impira AI",c:"Automation",d:"AI document understanding platform"},
{n:"Levity AI",c:"Automation",d:"AI workflow automation with image/text"},
{n:"Bardeen AI",c:"Automation",d:"AI browser automation and scraping"},
{n:"Browse AI",c:"Automation",d:"AI web scraping and monitoring"},
{n:"Apify AI",c:"Automation",d:"AI web scraping and automation platform"},
{n:"Phantombuster AI",c:"Automation",d:"AI data extraction and automation"},
{n:"Clay AI Automation",c:"Automation",d:"AI data and automation for outbound"},
{n:"Dripify AI",c:"Automation",d:"AI LinkedIn automation platform"},
{n:"Expandi AI",c:"Automation",d:"AI LinkedIn outreach automation"},
{n:"MeetAlfred AI",c:"Automation",d:"AI LinkedIn and email automation"},
{n:"Waalaxy AI",c:"Automation",d:"AI LinkedIn and email prospecting"},
{n:"Skylead AI",c:"Automation",d:"AI LinkedIn and email sequences"},
{n:"Lemlist Automation",c:"Automation",d:"AI-powered outreach automation"},
{n:"Outplay AI",c:"Automation",d:"AI multi-channel sales automation"},
{n:"Salesblink AI",c:"Automation",d:"AI cold email and outreach automation"},
{n:"QuickMail AI",c:"Automation",d:"AI email outreach platform"},
{n:"Mailshake AI",c:"Automation",d:"AI sales email automation"},
{n:"Hunter Campaigns AI",c:"Automation",d:"AI email campaign automation"},
{n:"Mixmax AI",c:"Automation",d:"AI email sequences and automation"},
{n:"Yesware AI",c:"Automation",d:"AI email tracking and outreach"},
{n:"Outreach Automation",c:"Automation",d:"AI sales engagement sequences"},
{n:"SalesLoft Automation",c:"Automation",d:"AI sales cadence automation"},
{n:"Apollo Automation",c:"Automation",d:"AI sales sequence automation"},
{n:"Calendly Automation",c:"Automation",d:"AI meeting scheduling workflows"},
{n:"Chili Piper AI",c:"Automation",d:"AI meeting booking for sales"},
{n:"Acuity AI",c:"Automation",d:"AI appointment scheduling automation"},
{n:"Hubspot Automation",c:"Automation",d:"AI marketing workflow automation"},
{n:"Marketo Automation",c:"Automation",d:"AI demand generation automation"},
{n:"Pardot Automation",c:"Automation",d:"AI B2B marketing automation"},
{n:"ActiveCampaign Automation",c:"Automation",d:"AI email and CRM automation"},
{n:"Drip Automation",c:"Automation",d:"AI e-commerce marketing automation"},
{n:"Klaviyo Automation",c:"Automation",d:"AI email and SMS automation"},
{n:"Omnisend Automation",c:"Automation",d:"AI omnichannel marketing automation"},
{n:"Braze Automation",c:"Automation",d:"AI cross-channel automation platform"},
{n:"Iterable Automation",c:"Automation",d:"AI growth marketing automation"},
{n:"Customer.io Automation",c:"Automation",d:"AI triggered messaging automation"},
{n:"Segment Automation",c:"Automation",d:"AI customer data and routing"},
{n:"Rudderstack AI",c:"Automation",d:"AI open-source data pipeline"},
{n:"Hightouch AI",c:"Automation",d:"AI data activation to destinations"},
{n:"Census AI",c:"Automation",d:"AI reverse ETL data sync"},
{n:"Fivetran AI",c:"Automation",d:"AI-assisted data pipeline"},
{n:"Airbyte AI",c:"Automation",d:"Open-source AI data integration"},
{n:"Stitch AI",c:"Automation",d:"AI simple ETL service"},
{n:"Matillion AI",c:"Automation",d:"AI cloud data transformation"},
{n:"dbt AI",c:"Automation",d:"AI-assisted data transformation"},
{n:"Prefect AI",c:"Automation",d:"AI Python workflow orchestration"},
{n:"Dagster AI",c:"Automation",d:"AI data orchestration platform"},
{n:"Apache Airflow AI",c:"Automation",d:"AI workflow orchestration platform"},
{n:"Luigi AI",c:"Automation",d:"AI Python workflow automation"},
{n:"Temporal AI",c:"Automation",d:"AI durable workflow execution"},
{n:"Conductor AI",c:"Automation",d:"AI microservice workflow engine"},
{n:"Camunda AI",c:"Automation",d:"AI process orchestration platform"},
{n:"Appian AI",c:"Automation",d:"AI low-code process automation"},
{n:"Pega AI",c:"Automation",d:"AI decisioning and BPM platform"},
{n:"ServiceNow AI",c:"Automation",d:"AI enterprise workflow platform"},
{n:"Monday Automations AI",c:"Automation",d:"AI no-code workflow automations"},
{n:"Airtable Automations",c:"Automation",d:"AI-triggered database actions"},
{n:"Notion Automations",c:"Automation",d:"AI automation in Notion workspace"},
{n:"ClickUp Automations",c:"Automation",d:"AI task and workflow automation"},
{n:"Asana Rules AI",c:"Automation",d:"AI automation rules in Asana"},
{n:"Jira Automation",c:"Automation",d:"AI-powered issue workflow rules"},
{n:"Linear Workflows AI",c:"Automation",d:"AI issue automation in Linear"},
{n:"GitHub Actions AI",c:"Automation",d:"AI CI/CD and automation workflows"},
{n:"GitLab CI AI",c:"Automation",d:"AI DevOps automation pipelines"},
]

// Also add Open Source, Local AI, AI Agents, LLMs tools from the existing seed

async function main() {
  console.log(`Processing ${ALL.length} tools...`)

  // Get all categories mapped by name
  const allCategories = await prisma.category.findMany()
  const catMap = new Map<string, string>()
  for (const c of allCategories) {
    catMap.set(c.name.toLowerCase(), c.id)
    catMap.set(c.slug, c.id)
  }

  // Map category name from the data to slug
  const nameToSlug: Record<string, string> = {
    "chat ai": "chat-ai", "coding": "coding", "image": "image", "video": "video",
    "voice": "voice", "marketing": "marketing", "writing": "writing",
    "productivity": "productivity", "business": "business", "education": "education",
    "automation": "automation", "open source": "open-source",
    "local ai": "local-ai", "ai agents": "ai-agents", "llms": "llms",
  }

  let created = 0, skipped = 0

  for (const tool of ALL) {
    const slug = tool.n.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")
    const existing = await prisma.aiTool.findUnique({ where: { slug } })
    if (existing) { skipped++; continue }

    const catSlug = nameToSlug[tool.c.toLowerCase()] || ""
    const catId = catMap.get(tool.c.toLowerCase()) || catMap.get(catSlug) || ""

    await prisma.aiTool.create({
      data: {
        name: tool.n,
        slug,
        tagline: tool.d,
        description: tool.d,
        websiteUrl: `https://www.google.com/search?q=${encodeURIComponent(tool.n + " AI")}`,
        logo: `https://www.google.com/s2/favicons?domain=${encodeURIComponent(tool.n.toLowerCase().replace(/\s+/g, "") + ".ai")}&sz=64`,
        pricing: "FREEMIUM",
        isPublished: true,
        featuredScore: 70,
        categories: catId ? { create: { categoryId: catId } } : undefined,
      },
    })
    created++
  }

  console.log(`Created: ${created}, Skipped: ${skipped}`)

  const cats = await prisma.category.findMany({ include: { _count: { select: { tools: true } } } })
  console.log("\nFinal category counts:")
  for (const c of cats.sort((a, b) => b._count.tools - a._count.tools)) {
    console.log(`  ${c.name}: ${c._count.tools} tools`)
  }

  await prisma.$disconnect()
}

main().catch((e) => { console.error(e); process.exit(1) })
